"""P01-04B2D integrated synthetic qualification of the accepted B1/B2A/B2B/B2C layers.

Every value frozen in this module is a **SYNTHETIC QUALIFICATION VECTOR**.  It is
**NOT REAL DATASET EVIDENCE**, **NOT A CANONICAL SPLIT** and **NOT A REAL LEAKAGE
AUDIT**.  Nothing here reads a dataset, a registry or a model, generates real
partition membership, performs a real leakage scan, or publishes anything.

The goldens below are literal constants.  They are never derived at test runtime
from the facade result under test, never regenerated by an option or a flag, and
never self-approved: a mismatch fails the qualification instead of updating a
golden (FD-B2D-7, FD-B2D-10, FD-B2D-11).

Two outcomes are expected and are *not* defects:

* ``constraint-stress-1000-v1`` reaches an intentionally infeasible boundary and
  the accepted ``allocate_indivisible_groups`` fails closed with
  ``SplitAllocationError``.  It implements no global minimum-deviation fallback,
  so the FD-B2-7 Fixture B criterion is recorded **UNSATISFIED**.
* The suite is therefore green while recording an unsatisfied P01-04B criterion.

```text
GREEN B2D QUALIFICATION CI DOES NOT EQUAL P01-04B ACCEPTANCE.

P01-04B acceptance eligibility:   FALSE
P01-04B acceptance recommendation: CHANGES REQUIRED
```

No production correction is made or authorized here.
"""

from __future__ import annotations

import builtins
import json
import os
import socket
import subprocess
import sys
from collections import Counter
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final

import pytest

from medscale import mesc as mesc_package
from medscale.mesc._canonical_json_v1 import sha256_of_bytes
from medscale.mesc._fixture_split_v1 import (
    FIXTURE_NAMESPACE_PREFIX,
    REQUEST_ID_PREFIX,
    SYNTHETIC_PROOF_PREFIX,
    FixtureIdentityMismatchError,
    FixtureOnlyModeError,
    FixtureSplitFacade,
    FixtureSplitRequest,
    FixtureSplitResult,
    InvalidFixtureRequestError,
)
from medscale.mesc._leakage_v1 import (
    CONTEXT_OVERLAP_THRESHOLD_PERCENT,
    NEAR_DUPLICATE_THRESHOLD_PERCENT,
    NORMALIZATION_RECORD,
    exact_context_equality,
    exact_example_identity,
    exact_question_equality,
    exact_source_document_identity,
    is_empty_normalized_question_pair,
    normalize_question,
    normalized_question_equality,
    question_token_set,
    token_set_jaccard,
)
from medscale.mesc._leakage_v1 import (
    DETECTION_METHODS as ACCEPTED_DETECTION_METHODS,
)
from medscale.mesc._split_v1 import (
    SplitAllocationError,
    SplitInputError,
    allocate_indivisible_groups,
    constrained_apportionment,
    join_labels,
)
from medscale.mesc.split import PilotSplitNotAuthorizedError, SourceDocumentGroupedSplitter

sys.path.insert(0, str(Path(__file__).resolve().parent))

import _mesc_p01_04b2d_fixtures_v1 as fx

# ===========================================================================
# SYNTHETIC QUALIFICATION VECTORS — frozen literals (FD-B2D-7)
# ===========================================================================


@dataclass(frozen=True, slots=True)
class GoldenVectors:
    """The complete frozen golden vector set for one successful fixture."""

    fixture_id: str
    synthetic_identity_proof: str
    fixture_sha256: str
    request_id: str
    split_hash: str
    split_fingerprint: str
    group_registry_sha256: str
    group_registry_byte_size: int
    example_registry_sha256: str
    example_registry_byte_size: int
    excluded_ledger_sha256: str
    excluded_ledger_byte_size: int
    summary_core_sha256: str
    summary_core_byte_size: int
    summary_document_sha256: str
    summary_document_byte_size: int
    audit_report_sha256: str
    audit_report_byte_size: int
    record_count: int
    group_count: int
    partition_counts: Mapping[str, int]
    group_counts_by_partition: Mapping[str, int]
    label_matrix: Mapping[str, Mapping[str, int]]
    excluded_count: int
    finding_count: int
    leaked: bool
    ordered_finding_ids: tuple[str, ...]


#: The ratified label matrix, keyed partition then decision, as the accepted
#: summary core emits it.
GOLDEN_LABEL_MATRIX: Final[Mapping[str, Mapping[str, int]]] = {
    "train": {"maybe": 77, "no": 237, "yes": 386},
    "validation": {"maybe": 17, "no": 50, "yes": 83},
    "test": {"maybe": 16, "no": 51, "yes": 83},
}

GOLDEN_PARTITION_COUNTS: Final[Mapping[str, int]] = {
    "train": 700,
    "validation": 150,
    "test": 150,
}

GOLDEN_EXCLUDED_LEDGER_SHA256: Final = (
    "786ba24fd619636052cfb3bd42b49f7bcaeb481e3745a8becb626dc064d80050"
)
GOLDEN_EXCLUDED_LEDGER_BYTE_SIZE: Final = 97

EXACT_REFERENCE_GOLDEN: Final = GoldenVectors(
    fixture_id="exact-reference-1000-v1",
    synthetic_identity_proof=(
        "mesc-synthetic-batch/1:sha256:"
        "737a4da3cd972ded8afccfbe6aa7e1913688ee2e589d5c77ed1d652c67540251"
    ),
    fixture_sha256="77fca47f59b78d2cf0e3fc7c65e39671aa319cb3d06f01216b47e0aaa2d790ed",
    request_id=(
        "mesc-pilot-01-fixture-request/1:sha256:"
        "870d37162f634099589e95b289408ea0d00d4e18eb1adb733dae553e2a88dfdc"
    ),
    split_hash="fb0cc27a531dada2",
    split_fingerprint="8931f7354310918e397454d7c3e7310c833ae4b8b7c329e3fec1617a099b4191",
    group_registry_sha256="4b924e668518ff7f0362ed8146b53de865ea6555e4fe8e35ed9bcf4147beef59",
    group_registry_byte_size=37036,
    example_registry_sha256="5977678620447931a48ab4a9f69454f3705aa04b496b234e415e2f78d8e1d4d0",
    example_registry_byte_size=343372,
    excluded_ledger_sha256=GOLDEN_EXCLUDED_LEDGER_SHA256,
    excluded_ledger_byte_size=GOLDEN_EXCLUDED_LEDGER_BYTE_SIZE,
    summary_core_sha256="5d679c6142b956ee58a3892d382306fafc99d467b6d9f22ce44c05f859dd3f11",
    summary_core_byte_size=518,
    summary_document_sha256="492b7b25933ed6d2f95c2d0ca23c48dc47ed224b5b835289d3114f1b250aca40",
    summary_document_byte_size=623,
    audit_report_sha256="59f30ea2dd86d761cd760db3fd46d921118c0605a978af847367ed0786ca5d62",
    audit_report_byte_size=485,
    record_count=1000,
    group_count=89,
    partition_counts=GOLDEN_PARTITION_COUNTS,
    group_counts_by_partition={"train": 59, "validation": 15, "test": 15},
    label_matrix=GOLDEN_LABEL_MATRIX,
    excluded_count=0,
    finding_count=0,
    leaked=False,
    ordered_finding_ids=(),
)

LEAKAGE_POSITIVE_GOLDEN: Final = GoldenVectors(
    fixture_id="leakage-positive-v1",
    synthetic_identity_proof=(
        "mesc-synthetic-batch/1:sha256:"
        "b6fcb96a1833e338d95f860c0aa71cd78f202024aa698361bce2bbf03a9bc9c7"
    ),
    fixture_sha256="0e95ae87eae09d1519e7e199f03319766e9ca0178eb208839c130bf6ba6b3ddc",
    request_id=(
        "mesc-pilot-01-fixture-request/1:sha256:"
        "0af0c9ca5a5db07d3f0accd2a3b037a814a8a204bf189b146f703e1b46296e15"
    ),
    split_hash="13e3a02558a2f4c3",
    split_fingerprint="e29a4d00a0807aca4909513de53c8220313f7c3338e6a99ece304a075ab9a7a6",
    group_registry_sha256="f6e6194faa525e10218322c08ff2175aaa94fb6a41630f229f657c63ddb551ff",
    group_registry_byte_size=371005,
    example_registry_sha256="72f7c144ca460e26d020de876a51ba03f38b00aeb7de8a634c835969753b87c7",
    example_registry_byte_size=339372,
    excluded_ledger_sha256=GOLDEN_EXCLUDED_LEDGER_SHA256,
    excluded_ledger_byte_size=GOLDEN_EXCLUDED_LEDGER_BYTE_SIZE,
    summary_core_sha256="2f0857ea707c567906a59a8c56353d606520e8af64c71f6d894011f5f9aa21a6",
    summary_core_byte_size=522,
    summary_document_sha256="a30e8a45a7d206e6988bc3a04ce743cd83e0c02efef680ef841eb274fff5f8ab",
    summary_document_byte_size=627,
    audit_report_sha256="4442288766756d023989452d6a218be619067d224b846f57f494592213d38087",
    audit_report_byte_size=6511,
    record_count=1000,
    group_count=999,
    partition_counts=GOLDEN_PARTITION_COUNTS,
    group_counts_by_partition={"train": 699, "validation": 150, "test": 150},
    label_matrix=GOLDEN_LABEL_MATRIX,
    excluded_count=0,
    finding_count=9,
    leaked=True,
    ordered_finding_ids=(
        "mesc-pilot-01-leakage-finding/1:sha256:"
        "3b99692d9830dc3bc9809de13739b9bc7dda819cc3b83b06f0fc5af8990cc598",
        "mesc-pilot-01-leakage-finding/1:sha256:"
        "6c43d43b55070b763ef9f320a87e383fb9c111160141895c77f6916f764002ec",
        "mesc-pilot-01-leakage-finding/1:sha256:"
        "7631055ca5042fe08c2f8eefdbbed530a865862ce14a7c4af14e44850e5f20d6",
        "mesc-pilot-01-leakage-finding/1:sha256:"
        "b45c28bc890eebbde0ca38426dc02d087fb8feded0aaeba9f584e79fc61f24d9",
        "mesc-pilot-01-leakage-finding/1:sha256:"
        "bb92d06768a1d4802e2090a3ddc03e31f806985b577401ace2b1e9319b3811aa",
        "mesc-pilot-01-leakage-finding/1:sha256:"
        "c239094e7ddec619b9b1ab6d8a306c881e469f16751fc6acf888717b3df925c6",
        "mesc-pilot-01-leakage-finding/1:sha256:"
        "d1ad045d2e7e1e20f6e3c20b09b0ab6bd891e32f2d82df70184e0814dfb0c9f0",
        "mesc-pilot-01-leakage-finding/1:sha256:"
        "d276ff8394e8f9116501f7357df6667e2c3691567e74b302f713517ac2c6bb95",
        "mesc-pilot-01-leakage-finding/1:sha256:"
        "e82b4391670e47ba204a91ca9fbec32732d17b0a627ae0570e035231abc8054b",
    ),
)

#: ``constraint-stress-1000-v1`` has no successful result document by design.
#: Its frozen expectation is the typed fail-closed outcome plus the infeasibility
#: proof and the frozen minimum-deviation matrices (FD-B2D-7).
CONSTRAINT_STRESS_SYNTHETIC_PROOF: Final = (
    "mesc-synthetic-batch/1:sha256:8a23da5649539025564260a8871f0e7b826d6cd20943cf531879bd7c4f44c40c"
)
CONSTRAINT_STRESS_FIXTURE_SHA256: Final = (
    "2b6a13c7f8f10d715f45b6cbd55ab2e31dab65253bab1508a39d965e87d63190"
)
CONSTRAINT_STRESS_REQUEST_ID: Final = (
    "mesc-pilot-01-fixture-request/1:sha256:"
    "77035c584291536520a3195e2b8ec73ae404b2f7419e5f8b427d1343406e1a88"
)
CONSTRAINT_STRESS_CROSSING_DOCUMENT: Final = "mesc-b2d-constraint-stress-1000-v1-yes-doc-0251"
CONSTRAINT_STRESS_CROSSING_RANK: Final = 234
CONSTRAINT_STRESS_ALLOCATION_MESSAGE: Final = (
    f"group {CONSTRAINT_STRESS_CROSSING_DOCUMENT!r} of size 2 would cross the "
    "yes/validation boundary with 1 places remaining"
)

GOLDENS: Final[Mapping[str, GoldenVectors]] = {
    EXACT_REFERENCE_GOLDEN.fixture_id: EXACT_REFERENCE_GOLDEN,
    LEAKAGE_POSITIVE_GOLDEN.fixture_id: LEAKAGE_POSITIVE_GOLDEN,
}

SUCCESSFUL_FIXTURE_IDS: Final[tuple[str, ...]] = tuple(GOLDENS)

#: Frozen classification and evidence-reference outcome of every leakage scenario,
#: in scenario order 1 through 9.
SCENARIO_CLASSIFICATIONS: Final[tuple[str, ...]] = (
    "false_positive",
    "false_positive",
    "unresolved",
    "unresolved",
    "unresolved",
    "unresolved",
    "unresolved",
    "unresolved",
    "false_positive",
)
SCENARIO_EVIDENCE_OUTCOMES: Final[tuple[str, ...]] = (
    "mesc-pilot-01-b2d-leakage-scenario/1/exact-example-self-control",
    "mesc-pilot-01-b2d-leakage-scenario/1/expected-same-group-source-document",
    "absent",
    "absent",
    "absent",
    "absent",
    "absent",
    "absent",
    "mesc-pilot-01-b2d-leakage-scenario/1/whitespace-only-control",
)
SCENARIO_FINDING_TYPES: Final[tuple[str, ...]] = (
    "exact_example",
    "source_document",
    "exact_question",
    "normalized_question",
    "near_duplicate_question",
    "near_duplicate_question",
    "context_overlap",
    "context_overlap",
    "empty_normalized_question",
)
SCENARIO_SCORE_REPRESENTATIONS: Final[tuple[str, ...]] = (
    "none",
    "none",
    "none",
    "none",
    "jaccard:9/10",
    "jaccard:10/11",
    "none",
    "jaccard:19/20",
    "not_evaluable",
)

FALSE_POSITIVE_COUNT: Final = 3
UNRESOLVED_COUNT: Final = 6
SUPPRESSED_COUNT: Final = 0

#: The two same-partition synthetic controls.  They qualify primitive behaviour,
#: finding construction, canonical identity, classification and evidence-reference
#: enforcement only.  They are NOT cross-partition leakage, do NOT establish
#: duplicate partition membership or source-document overlap, and are NOT a real
#: or canonical leakage audit (FD-B2D-6 §8.6).
SAME_PARTITION_CONTROL_INDICES: Final[tuple[int, ...]] = (1, 2)

# ===========================================================================
# P01-04B criteria mapping (FD-B2D-9) — 13 unique criteria
# ===========================================================================

SATISFIED: Final = "SATISFIED"
UNSATISFIED: Final = "UNSATISFIED"
BLOCKED: Final = "BLOCKED"
NOT_APPLICABLE: Final = "NOT APPLICABLE"

ALLOWED_STATUSES: Final[tuple[str, ...]] = (SATISFIED, UNSATISFIED, BLOCKED, NOT_APPLICABLE)


@dataclass(frozen=True, slots=True)
class Criterion:
    """One P01-04B criterion, its bounded B2D disposition and its proving test."""

    number: int | None
    key: str
    statement: str
    status: str
    test_symbol: str
    p01_04b_consequence: str


P01_04B_CRITERIA: Final[tuple[Criterion, ...]] = (
    Criterion(
        number=1,
        key="public-splitter-fail-closed",
        statement="SourceDocumentGroupedSplitter.assign remains unconditionally fail-closed",
        status=SATISFIED,
        test_symbol="test_criterion_01_public_splitter_remains_fail_closed",
        p01_04b_consequence="SATISFIED for P01-04B",
    ),
    Criterion(
        number=2,
        key="separate-fixture-facade",
        statement="FixtureSplitFacade exists as the separate fixture-only facade",
        status=SATISFIED,
        test_symbol="test_criterion_02_separate_fixture_only_facade",
        p01_04b_consequence="SATISFIED for P01-04B",
    ),
    Criterion(
        number=3,
        key="library-only-in-memory",
        statement="the qualification path is library-only and in-memory",
        status=SATISFIED,
        test_symbol="test_criterion_03_library_only_in_memory_path",
        p01_04b_consequence="SATISFIED for P01-04B",
    ),
    Criterion(
        number=4,
        key="no-b2-cli",
        statement="no B2 CLI exists",
        status=SATISFIED,
        test_symbol="test_criterion_04_no_b2_cli_exists",
        p01_04b_consequence="SATISFIED for P01-04B",
    ),
    Criterion(
        number=5,
        key="authoritative-fingerprint",
        statement="the 64-hex split_fingerprint is authoritative",
        status=SATISFIED,
        test_symbol="test_criterion_05_split_fingerprint_is_authoritative",
        p01_04b_consequence="SATISFIED for P01-04B",
    ),
    Criterion(
        number=6,
        key="compatibility-split-hash",
        statement="the 16-hex split_hash is compatibility/display only",
        status=SATISFIED,
        test_symbol="test_criterion_06_split_hash_is_compatibility_only",
        p01_04b_consequence="SATISFIED for P01-04B",
    ),
    Criterion(
        number=7,
        key="fd-b2-6-normalization",
        statement="leakage normalization follows FD-B2-6",
        status=SATISFIED,
        test_symbol="test_criterion_07_leakage_normalization_follows_fd_b2_6",
        p01_04b_consequence="SATISFIED for P01-04B",
    ),
    Criterion(
        number=8,
        key="three-named-fixtures",
        statement="exactly the three named fixtures form the suite",
        status=SATISFIED,
        test_symbol="test_criterion_08_exactly_three_named_fixtures",
        p01_04b_consequence="SATISFIED for P01-04B",
    ),
    Criterion(
        number=9,
        key="byte-identical-results",
        statement="stable synthetic inputs produce byte-identical results",
        status=SATISFIED,
        test_symbol="test_criterion_09_stable_inputs_are_byte_identical",
        p01_04b_consequence="SATISFIED for P01-04B",
    ),
    Criterion(
        number=10,
        key="no-real-p01-03g-membership",
        statement="no real P01-03G membership is generated or disclosed",
        status=SATISFIED,
        test_symbol="test_criterion_10_no_real_p01_03g_membership",
        p01_04b_consequence="SATISFIED for P01-04B",
    ),
    Criterion(
        number=11,
        key="atomic-publication",
        statement="atomic publication",
        status=NOT_APPLICABLE,
        test_symbol="test_criterion_11_atomic_publication_not_applicable",
        p01_04b_consequence=(
            "NOT APPLICABLE to B2D; NOT SATISFIED for P01-04B overall. "
            "FixtureSplitFacade performs no filesystem publication and no "
            "publication capability or acceptance is created."
        ),
    ),
    Criterion(
        number=12,
        key="write-path-protections",
        statement="write-path protections",
        status=NOT_APPLICABLE,
        test_symbol="test_criterion_12_write_path_protections_not_applicable",
        p01_04b_consequence=(
            "NOT APPLICABLE to B2D; NOT SATISFIED for P01-04B overall. "
            "The absence of a write path is not qualification of a future write path."
        ),
    ),
    Criterion(
        number=13,
        key="date-free-promotable-artifacts",
        statement="date-free promotable artifacts",
        status=NOT_APPLICABLE,
        test_symbol="test_criterion_13_date_free_canonical_byte_surfaces",
        p01_04b_consequence=(
            "NOT APPLICABLE to B2D output promotion; the date-free canonical-byte "
            "invariant is testable and asserted, but a successful assertion does not "
            "make any B2D output promotable."
        ),
    ),
    Criterion(
        number=None,
        key="indivisible-group-minimum-deviation",
        statement=("indivisible-group global minimum-deviation allocation (FD-B2-7 Fixture B)"),
        status=UNSATISFIED,
        test_symbol="test_constraint_stress_fails_closed_with_the_accepted_typed_error",
        p01_04b_consequence=(
            "UNSATISFIED. allocate_indivisible_groups performs exact-target "
            "allocation only and raises SplitAllocationError at a boundary crossing; "
            "it implements no global minimum-deviation fallback. No production "
            "correction is authorized or made in B2D."
        ),
    ),
)

#: The count of unique numbered P01-04B criteria the mapping must cover.
UNIQUE_CRITERION_COUNT: Final = 13

P01_04B_ACCEPTANCE_ELIGIBILITY: Final = False
P01_04B_ACCEPTANCE_RECOMMENDATION: Final = "CHANGES REQUIRED"
P01_04B_STATUS: Final = "INCOMPLETE / NOT ACCEPTED"
GREEN_CI_MEANING: Final = "GREEN B2D QUALIFICATION CI DOES NOT EQUAL P01-04B ACCEPTANCE"


def acceptance_eligible(criteria: tuple[Criterion, ...]) -> bool:
    """Return whether every criterion is SATISFIED.

    A ``NOT APPLICABLE`` disposition records that B2D cannot qualify a criterion.
    It never converts to ``SATISFIED`` and never counts toward acceptance, and
    an ``UNSATISFIED`` or ``BLOCKED`` criterion can never be ignored.
    """
    return all(criterion.status == SATISFIED for criterion in criteria)


# ===========================================================================
# Request construction — literals in, nothing derived from the code under test
# ===========================================================================

_IDENTITIES: Final[Mapping[str, tuple[str, str, str]]] = {
    "exact-reference-1000-v1": (
        EXACT_REFERENCE_GOLDEN.synthetic_identity_proof,
        EXACT_REFERENCE_GOLDEN.fixture_sha256,
        EXACT_REFERENCE_GOLDEN.request_id,
    ),
    "constraint-stress-1000-v1": (
        CONSTRAINT_STRESS_SYNTHETIC_PROOF,
        CONSTRAINT_STRESS_FIXTURE_SHA256,
        CONSTRAINT_STRESS_REQUEST_ID,
    ),
    "leakage-positive-v1": (
        LEAKAGE_POSITIVE_GOLDEN.synthetic_identity_proof,
        LEAKAGE_POSITIVE_GOLDEN.fixture_sha256,
        LEAKAGE_POSITIVE_GOLDEN.request_id,
    ),
}


def request_kwargs(fixture_id: str, **overrides: Any) -> dict[str, Any]:
    """Return the exact request keyword arguments for one fixture.

    The three identity values are committed literal constants.  The facade
    regenerates and compares both digests itself, so supplying literals here is
    the fail-closed proof that the frozen identities are the real ones.
    """
    inputs = fx.fixture_inputs(fixture_id)
    proof, fixture_sha256, request_id = _IDENTITIES[fixture_id]
    kwargs: dict[str, Any] = {
        "fixture_schema_version": "1",
        "fixture_namespace": FIXTURE_NAMESPACE_PREFIX + fixture_id,
        "fixture_id": fixture_id,
        "fixture_sha256": fixture_sha256,
        "fixture_only": True,
        "non_evidence": True,
        "synthetic_identity_proof": proof,
        "request_id": request_id,
        "seed": fx.SEED,
        "policy_id": fx.POLICY_ID,
        "transformation_version": fx.TRANSFORMATION_VERSION,
        "ordered_rows": inputs.plan.ordered_rows,
        "source_labels": inputs.plan.source_labels,
        "partition_totals": dict(inputs.partition_totals),
        "leakage_findings": inputs.leakage_findings,
        "detection_methods": inputs.detection_methods,
        "execution_evidence_ref": inputs.execution_evidence_ref,
    }
    kwargs.update(overrides)
    return kwargs


def build_request(fixture_id: str, **overrides: Any) -> FixtureSplitRequest:
    """Return the exact ``FixtureSplitRequest`` for one qualification fixture."""
    return FixtureSplitRequest(**request_kwargs(fixture_id, **overrides))


def byte_surfaces(result: FixtureSplitResult) -> dict[str, bytes]:
    """Return every canonical byte surface the facade produced."""
    return {
        "group_registry": result.group_registry_bytes,
        "example_registry": result.example_registry_bytes,
        "excluded_ledger": result.excluded_ledger_bytes,
        "split_summary_identity_core": result.split_summary_identity_core_bytes,
        "split_summary_document": result.split_summary_document_bytes,
        "leakage_audit_report": result.audit_report_bytes,
        "fingerprint_identity": result.split_fingerprint_record.identity.canonical_bytes(),
    }


def digest_report() -> dict[str, object]:
    """Return every observed identity value, for cross-process comparison.

    This is the *observed* report.  It is compared against the frozen literals,
    never used to produce them.
    """
    report: dict[str, object] = {}
    for fixture_id in SUCCESSFUL_FIXTURE_IDS:
        result = FixtureSplitFacade.run(build_request(fixture_id))
        report[fixture_id] = {
            "synthetic_identity_proof": fx.synthetic_identity_proof(fixture_id),
            "request_id": result.request_id,
            "split_hash": result.split_manifest.computed_split_hash,
            "split_fingerprint": result.split_fingerprint_record.split_fingerprint,
            "surfaces": {
                name: [sha256_of_bytes(payload), len(payload)]
                for name, payload in byte_surfaces(result).items()
            },
        }
    stress = fx.CONSTRAINT_STRESS_FIXTURE_ID
    try:
        FixtureSplitFacade.run(build_request(stress))
    except SplitAllocationError as error:
        report[stress] = {
            "synthetic_identity_proof": fx.synthetic_identity_proof(stress),
            "error_type": type(error).__name__,
            "error_message": str(error),
        }
    else:  # pragma: no cover - the accepted implementation always fails closed here
        report[stress] = {"error_type": "NONE", "error_message": ""}
    return report


def cross_process_digest_report() -> str:
    """Return :func:`digest_report` as sorted canonical JSON text."""
    return json.dumps(digest_report(), sort_keys=True, separators=(",", ":"))


@pytest.fixture(scope="module")
def exact_reference_result() -> FixtureSplitResult:
    return FixtureSplitFacade.run(build_request(fx.EXACT_REFERENCE_FIXTURE_ID))


@pytest.fixture(scope="module")
def leakage_positive_result() -> FixtureSplitResult:
    return FixtureSplitFacade.run(build_request(fx.LEAKAGE_POSITIVE_FIXTURE_ID))


@pytest.fixture(scope="module")
def results(
    exact_reference_result: FixtureSplitResult, leakage_positive_result: FixtureSplitResult
) -> dict[str, FixtureSplitResult]:
    return {
        fx.EXACT_REFERENCE_FIXTURE_ID: exact_reference_result,
        fx.LEAKAGE_POSITIVE_FIXTURE_ID: leakage_positive_result,
    }


# ===========================================================================
# 1. Shared fixture identity contract (FD-B2D-2, FD-B2D-3)
# ===========================================================================


def test_exactly_the_three_ratified_fixture_names_form_the_suite() -> None:
    assert fx.FIXTURE_IDS == (
        "exact-reference-1000-v1",
        "constraint-stress-1000-v1",
        "leakage-positive-v1",
    ), "the qualification suite must be exactly the three ratified fixture names"


def test_no_generic_fixture_alias_and_no_fourth_fixture() -> None:
    assert len(fx.FIXTURE_IDS) == 3, "no fourth qualification fixture is permitted"
    assert len(set(fx.FIXTURE_IDS)) == 3, "the three fixture names must be distinct"
    assert "fixture-1000-v1" not in fx.FIXTURE_IDS, "no generic fixture alias is permitted"


@pytest.mark.parametrize("fixture_id", fx.FIXTURE_IDS)
def test_every_fixture_has_exactly_one_thousand_rows_and_labels(fixture_id: str) -> None:
    plan = fx.build_plan(fixture_id)
    assert len(plan.ordered_rows) == 1000, f"{fixture_id} must have exactly 1000 OrderedExampleRow"
    assert len(plan.source_labels) == 1000, f"{fixture_id} must have exactly 1000 SourceLabelRow"


@pytest.mark.parametrize("fixture_id", fx.FIXTURE_IDS)
def test_row_ordinals_are_zero_through_nine_hundred_and_ninety_nine(fixture_id: str) -> None:
    plan = fx.build_plan(fixture_id)
    ordinals = sorted(row.row_ordinal for row in plan.ordered_rows)
    assert ordinals == list(range(1000)), f"{fixture_id} row ordinals must be 0..999 inclusive"


@pytest.mark.parametrize("fixture_id", fx.FIXTURE_IDS)
def test_original_example_ids_follow_the_ratified_pattern(fixture_id: str) -> None:
    plan = fx.build_plan(fixture_id)
    for row in plan.ordered_rows:
        expected = f"mesc-b2d-{fixture_id}-example-{row.row_ordinal:04d}"
        assert row.original_example_id == expected, (
            f"{fixture_id} original_example_id must be {expected!r}, "
            f"got {row.original_example_id!r}"
        )


@pytest.mark.parametrize("fixture_id", fx.FIXTURE_IDS)
def test_label_totals_match_the_ratified_totals(fixture_id: str) -> None:
    plan = fx.build_plan(fixture_id)
    totals = Counter(label.decision for label in plan.source_labels)
    assert dict(totals) == {"yes": 552, "no": 338, "maybe": 110}, (
        f"{fixture_id} label totals must be yes 552 / no 338 / maybe 110, got {dict(totals)}"
    )


@pytest.mark.parametrize("fixture_id", fx.FIXTURE_IDS)
def test_source_record_hash_is_the_ratified_domain_digest(fixture_id: str) -> None:
    plan = fx.build_plan(fixture_id)
    for label in plan.source_labels:
        domain = (
            f"mesc-pilot-01-b2d-source-record-v1|{fixture_id}|{label.original_example_id}"
            f"|{label.source_document_id}|{label.decision}"
        )
        expected = sha256_of_bytes(domain.encode("utf-8"))
        assert label.source_record_hash == expected, (
            f"{fixture_id} source_record_hash must digest the exact ratified ASCII domain string"
        )
        assert len(label.source_record_hash) == 64, "source_record_hash must be 64 hex characters"


@pytest.mark.parametrize("fixture_id", fx.FIXTURE_IDS)
def test_dataset_identity_is_the_frozen_synthetic_identity(fixture_id: str) -> None:
    plan = fx.build_plan(fixture_id)
    identities = {
        (label.dataset_id, label.dataset_revision, label.configuration)
        for label in plan.source_labels
    }
    assert identities == {
        ("mesc-pilot-01-synthetic-qualification", "p01-04b2d-v1", "b2d-synthetic-qualification")
    }, f"{fixture_id} must carry exactly the frozen synthetic dataset identity"


@pytest.mark.parametrize("fixture_id", fx.FIXTURE_IDS)
def test_no_group_crosses_a_decision_stratum(fixture_id: str) -> None:
    plan = fx.build_plan(fixture_id)
    decisions_by_document: dict[str, set[str]] = {}
    for group in plan.groups:
        decisions_by_document.setdefault(group.source_document_id, set()).add(group.decision)
    offenders = {
        document: values for document, values in decisions_by_document.items() if len(values) != 1
    }
    assert not offenders, f"{fixture_id} source-document groups must be homogeneous: {offenders}"


@pytest.mark.parametrize("fixture_id", fx.FIXTURE_IDS)
def test_generator_spec_has_exactly_the_fourteen_ratified_members(fixture_id: str) -> None:
    document = fx.generator_spec_document(fixture_id)
    assert sorted(document) == sorted(
        [
            "schema",
            "fixture_id",
            "fixture_schema_version",
            "generator_version",
            "dataset_id",
            "dataset_revision",
            "configuration",
            "transformation_version",
            "policy_id",
            "row_count",
            "partition_totals",
            "label_totals",
            "grouping_contract",
            "leakage_scenario_contract",
        ]
    ), f"{fixture_id} generator specification must have exactly the fourteen ratified members"
    assert document["schema"] == "mesc-pilot-01-b2d-generator-spec/1"
    assert document["generator_version"] == "mesc-pilot-01-b2d-generator/1"
    assert document["row_count"] == 1000


@pytest.mark.parametrize("fixture_id", fx.FIXTURE_IDS)
def test_generator_spec_binds_no_facade_output_or_runtime_value(fixture_id: str) -> None:
    """The proof must be computable before the facade runs (anti-circularity)."""
    text = json.dumps(fx.generator_spec_document(fixture_id), sort_keys=True)
    forbidden = (
        "fixture_sha256",
        "request_id",
        "split_hash",
        "split_fingerprint",
        "runtime",
        "python",
        "timestamp",
        "workflow",
    )
    for token in forbidden:
        assert token not in text, f"{fixture_id} generator specification must not bind {token!r}"


@pytest.mark.parametrize(
    ("fixture_id", "expected"),
    [
        ("exact-reference-1000-v1", EXACT_REFERENCE_GOLDEN.synthetic_identity_proof),
        ("constraint-stress-1000-v1", CONSTRAINT_STRESS_SYNTHETIC_PROOF),
        ("leakage-positive-v1", LEAKAGE_POSITIVE_GOLDEN.synthetic_identity_proof),
    ],
)
def test_synthetic_identity_proof_matches_its_frozen_literal(
    fixture_id: str, expected: str
) -> None:
    observed = fx.synthetic_identity_proof(fixture_id)
    assert observed.startswith(SYNTHETIC_PROOF_PREFIX), (
        f"{fixture_id} proof must carry the authorized mesc-synthetic-batch/1 prefix"
    )
    assert observed == expected, (
        f"{fixture_id} synthetic_identity_proof drifted from its frozen literal; "
        "a golden change requires a separate founder decision"
    )


@pytest.mark.parametrize("fixture_id", fx.FIXTURE_IDS)
def test_fixture_namespace_is_derived_from_the_fixture_id(fixture_id: str) -> None:
    inputs = fx.fixture_inputs(fixture_id)
    assert inputs.fixture_namespace == f"mesc-fixture/p01-04b2/1/{fixture_id}"
    assert inputs.fixture_namespace == FIXTURE_NAMESPACE_PREFIX + fixture_id


@pytest.mark.parametrize("fixture_id", fx.FIXTURE_IDS)
def test_detection_methods_are_the_exact_ratified_caller_order(fixture_id: str) -> None:
    inputs = fx.fixture_inputs(fixture_id)
    assert inputs.detection_methods == (
        "exact_context_equality",
        "exact_example_identity",
        "exact_question_equality",
        "exact_source_document_identity",
        "normalize_question",
        "normalized_question_equality",
        "token_set_jaccard",
        "tokenize",
    ), "detection methods must be the exact ratified tuple in the ratified caller order"
    assert set(inputs.detection_methods) <= set(ACCEPTED_DETECTION_METHODS), (
        "every detection method must be in the accepted B2B allowlist"
    )


# ===========================================================================
# 2. exact-reference-1000-v1 (FD-B2D-4)
# ===========================================================================


def test_exact_reference_has_eighty_nine_groups() -> None:
    plan = fx.build_plan(fx.EXACT_REFERENCE_FIXTURE_ID)
    assert plan.group_count == 89, "exact-reference-1000-v1 must have exactly 89 groups"


def test_exact_reference_group_counts_by_decision() -> None:
    plan = fx.build_plan(fx.EXACT_REFERENCE_FIXTURE_ID)
    counts = {decision: len(plan.groups_for(decision)) for decision in fx.DECISIONS}
    assert counts == {"yes": 45, "no": 31, "maybe": 13}, (
        f"exact-reference group counts must be yes 45 / no 31 / maybe 13, got {counts}"
    )


def test_exact_reference_contains_all_six_required_group_sizes() -> None:
    plan = fx.build_plan(fx.EXACT_REFERENCE_FIXTURE_ID)
    sizes = set(plan.group_sizes())
    assert set(fx.REQUIRED_GROUP_SIZES) <= sizes, (
        f"group sizes 1, 2, 3, 5, 8 and 13 must all be present, got {sorted(sizes)}"
    )


def test_exact_reference_group_size_histogram_is_frozen() -> None:
    plan = fx.build_plan(fx.EXACT_REFERENCE_FIXTURE_ID)
    histogram = dict(Counter(plan.group_sizes()))
    assert histogram == {13: 72, 8: 4, 5: 2, 3: 5, 2: 1, 1: 5}, (
        f"exact-reference group-size histogram drifted: {histogram}"
    )


def test_exact_reference_size_vectors_sum_to_the_ratified_matrix() -> None:
    for decision in fx.DECISIONS:
        for partition in fx.PARTITIONS:
            vector = fx.GROUP_SIZE_VECTORS[decision][partition]
            expected = fx.RATIFIED_MATRIX[decision][partition]
            assert sum(vector) == expected, (
                f"{decision}/{partition} size vector sums to {sum(vector)}, expected {expected}"
            )


def test_exact_reference_ranked_order_binds_the_size_vector_positionally() -> None:
    """The independent D6 rank order is what the size vector is bound to."""
    plan = fx.build_plan(fx.EXACT_REFERENCE_FIXTURE_ID)
    for decision in fx.DECISIONS:
        groups = plan.groups_for(decision)
        expected = fx.concatenated_size_vector(decision)
        assert tuple(group.size for group in groups) == expected, (
            f"{decision} ranked group sizes must equal the concatenated ratified vector"
        )
        keys = [fx.d6_partition_key(decision, group.source_document_id) for group in groups]
        assert keys == sorted(keys), f"{decision} candidates must be in ascending D6 digest order"


def test_exact_reference_every_partition_holds_multiple_multi_example_groups() -> None:
    plan = fx.build_plan(fx.EXACT_REFERENCE_FIXTURE_ID)
    placement = fx.independent_partition_by_row(plan)
    multi: Counter[str] = Counter()
    for group in plan.groups:
        if group.size > 1:
            multi[placement[group.row_ordinals[0]]] += 1
    assert dict(multi) == {"train": 56, "validation": 14, "test": 14}, (
        f"every partition must hold multiple multi-example groups, got {dict(multi)}"
    )


def test_exact_reference_exact_matrix_is_feasible_for_the_independent_oracle() -> None:
    plan = fx.build_plan(fx.EXACT_REFERENCE_FIXTURE_ID)
    matrix = fx.independent_label_matrix(plan)
    assert matrix == {
        "train": {"yes": 386, "no": 237, "maybe": 77},
        "validation": {"yes": 83, "no": 50, "maybe": 17},
        "test": {"yes": 83, "no": 51, "maybe": 16},
    }, "the independent oracle must reproduce the exact ratified matrix"


def test_exact_reference_facade_reproduces_the_independent_plan(
    exact_reference_result: FixtureSplitResult,
) -> None:
    """The facade must independently reproduce the plan derived without B1 ranking."""
    plan = fx.build_plan(fx.EXACT_REFERENCE_FIXTURE_ID)
    placement = fx.independent_partition_by_row(plan)
    documents = plan.document_of_row()
    expected_by_document: dict[str, str] = {}
    for ordinal, partition in placement.items():
        expected_by_document[documents[ordinal]] = partition
    observed: dict[str, str] = {}
    for record in exact_reference_result.split_manifest.split_assignments:
        observed[record.source_document_id] = record.split
    assert observed == expected_by_document, (
        "the facade's source-document placement must equal the independent oracle's placement"
    )


def test_exact_reference_has_a_clean_leakage_report(
    exact_reference_result: FixtureSplitResult,
) -> None:
    report = exact_reference_result.audit_report
    assert report.finding_count == 0, "exact-reference must produce a clean leakage report"
    assert report.leaked is False, "exact-reference must not be marked leaked"


def test_exact_reference_excludes_nothing(exact_reference_result: FixtureSplitResult) -> None:
    core = exact_reference_result.split_summary_identity_core
    assert core.excluded_record_count == 0, "B2C authorizes no exclusion"


# ===========================================================================
# 3. constraint-stress-1000-v1 (FD-B2D-5)
# ===========================================================================


def test_constraint_stress_has_five_hundred_groups_of_size_two() -> None:
    plan = fx.build_plan(fx.CONSTRAINT_STRESS_FIXTURE_ID)
    assert plan.group_count == 500, "constraint-stress-1000-v1 must have exactly 500 groups"
    assert set(plan.group_sizes()) == {2}, "every constraint-stress group must have size exactly 2"


def test_constraint_stress_group_counts_by_decision() -> None:
    plan = fx.build_plan(fx.CONSTRAINT_STRESS_FIXTURE_ID)
    counts = {decision: len(plan.groups_for(decision)) for decision in fx.DECISIONS}
    assert counts == {"yes": 276, "no": 169, "maybe": 55}, (
        f"constraint-stress group counts must be yes 276 / no 169 / maybe 55, got {counts}"
    )


def test_ratified_matrix_has_exactly_six_odd_cells_and_five_distinct_odd_values() -> None:
    """The count is six cells, not five; five is the number of distinct odd values."""
    odd = fx.odd_target_cells()
    assert len(odd) == 6, f"the ratified target matrix must have exactly six odd cells, got {odd}"
    assert {cell[2] for cell in odd} == {83, 237, 51, 77, 17}, (
        "the six odd cells comprise five distinct odd values because 83 occurs twice"
    )
    assert [cell[:2] for cell in odd] == [
        ("yes", "validation"),
        ("yes", "test"),
        ("no", "train"),
        ("no", "test"),
        ("maybe", "train"),
        ("maybe", "validation"),
    ], "the six odd cells must be exactly the ratified ones"


def test_constraint_stress_infeasibility_is_proved_mechanically() -> None:
    """Every realized cell must be even, so the six odd target cells are unreachable."""
    plan = fx.build_plan(fx.CONSTRAINT_STRESS_FIXTURE_ID)
    assert set(plan.group_sizes()) == {2}, "the parity argument requires every group to be size 2"
    outcome = fx.minimum_deviation_result()
    assert outcome.exact_matrix_feasible is False, (
        "the exact ratified matrix must be provably infeasible under indivisible pairs"
    )
    for _, partition, value in fx.odd_target_cells():
        assert value % 2 == 1, f"{partition} target cell must be odd for the parity argument"


def test_minimum_deviation_enumeration_region_is_provably_complete() -> None:
    """Any matrix scoring at most 6 has every cell deviation bounded by 2.

    ``3 ** 2 = 9 > 6``, so no cell of a score-6-or-better matrix can deviate by
    more than 2; and a matrix is uniquely determined by its free 2x2 block once
    the row and column totals are fixed.  The enumeration radius therefore
    strictly contains every candidate optimum, which makes the bounded search a
    complete derivation rather than a sample.
    """
    assert fx.SCORE_SIX_CELL_BOUND**2 <= fx.MINIMUM_DEVIATION_SCORE, (
        "the per-cell bound must be consistent with the frozen minimum score"
    )
    assert (fx.SCORE_SIX_CELL_BOUND + 1) ** 2 > fx.MINIMUM_DEVIATION_SCORE, (
        "a deviation of 3 must already exceed the frozen minimum score"
    )
    assert fx.FREE_BLOCK_RADIUS > fx.SCORE_SIX_CELL_BOUND, (
        "the enumeration radius must strictly exceed the proven per-cell bound"
    )


def test_minimum_deviation_oracle_finds_exactly_two_score_six_matrices() -> None:
    outcome = fx.minimum_deviation_result()
    assert outcome.minimum_score == 6, (
        f"the minimum squared-deviation score must be 6, got {outcome.minimum_score}"
    )
    assert len(outcome.optimal_matrices) == 2, (
        f"exactly two feasible matrices must attain score 6, got {len(outcome.optimal_matrices)}"
    )
    assert outcome.optimal_matrices[0] == fx.MATRIX_A, (
        "the lexicographic winner must be the frozen Matrix A"
    )
    assert outcome.optimal_matrices[1] == fx.MATRIX_B, (
        "the score-6 runner-up must be the frozen Matrix B"
    )


def test_frozen_matrix_a_and_b_are_the_exact_ratified_vectors() -> None:
    assert fx.MATRIX_A == (386, 82, 84, 238, 50, 50, 76, 18, 16), "Matrix A vector drifted"
    assert fx.MATRIX_B == (386, 84, 82, 236, 50, 52, 78, 16, 16), "Matrix B vector drifted"


def test_matrix_a_is_lexicographically_smaller_than_matrix_b() -> None:
    """Label order yes, no, maybe; partition order train, validation, test."""
    assert fx.MATRIX_A < fx.MATRIX_B, "Matrix A must be the lexicographic winner"
    first_difference = next(index for index in range(9) if fx.MATRIX_A[index] != fx.MATRIX_B[index])
    assert first_difference == 1, "the first differing position must be validation under yes"
    assert (fx.MATRIX_A[1], fx.MATRIX_B[1]) == (82, 84), (
        "Matrix A must hold 82 and Matrix B 84 at yes/validation"
    )


@pytest.mark.parametrize("matrix", [fx.MATRIX_A, fx.MATRIX_B])
def test_both_score_six_matrices_are_feasible_and_score_exactly_six(
    matrix: tuple[int, ...],
) -> None:
    rows, columns = fx.matrix_totals(matrix)
    assert rows == (552, 338, 110), f"row totals must be 552 / 338 / 110, got {rows}"
    assert columns == (700, 150, 150), f"column totals must be 700 / 150 / 150, got {columns}"
    assert all(value >= 0 and value % 2 == 0 for value in matrix), (
        "every cell must be a non-negative even integer"
    )
    assert fx.squared_deviation(matrix) == 6, "the frozen matrix must score exactly 6"


def test_deviation_of_matrix_a_from_the_ratified_matrix_is_frozen() -> None:
    deviations = tuple(
        value - base for value, base in zip(fx.MATRIX_A, fx.ratified_vector(), strict=True)
    )
    assert deviations == (0, -1, 1, 1, 0, -1, -1, 1, 0), "Matrix A deviation vector drifted"


def test_deviation_of_matrix_b_from_the_ratified_matrix_is_frozen() -> None:
    deviations = tuple(
        value - base for value, base in zip(fx.MATRIX_B, fx.ratified_vector(), strict=True)
    )
    assert deviations == (0, 1, -1, -1, 0, 1, 1, -1, 0), "Matrix B deviation vector drifted"


def test_no_feasible_matrix_scores_better_than_six() -> None:
    outcome = fx.minimum_deviation_result()
    assert outcome.feasible_count > len(outcome.optimal_matrices), (
        "the enumeration must cover more than the optimal matrices alone"
    )
    assert outcome.minimum_score == fx.MINIMUM_DEVIATION_SCORE


def test_constraint_stress_independent_oracle_also_refuses_to_allocate() -> None:
    plan = fx.build_plan(fx.CONSTRAINT_STRESS_FIXTURE_ID)
    with pytest.raises(fx.IndependentAllocationInfeasibleError) as caught:
        fx.independent_partition_by_row(plan)
    assert CONSTRAINT_STRESS_CROSSING_DOCUMENT in str(caught.value), (
        "the independent oracle must refuse at the same frozen crossing document"
    )


def test_constraint_stress_crossing_group_is_at_the_frozen_rank() -> None:
    plan = fx.build_plan(fx.CONSTRAINT_STRESS_FIXTURE_ID)
    groups = plan.groups_for("yes")
    ranks = [
        index
        for index, group in enumerate(groups)
        if group.source_document_id == CONSTRAINT_STRESS_CROSSING_DOCUMENT
    ]
    assert ranks == [CONSTRAINT_STRESS_CROSSING_RANK], (
        f"the crossing group must sit at rank {CONSTRAINT_STRESS_CROSSING_RANK}, got {ranks}"
    )
    # 193 pairs fill train exactly (386), then 41 pairs fill 82 of validation's 83.
    assert 2 * CONSTRAINT_STRESS_CROSSING_RANK == 468, (
        "468 yes examples must be placed before the crossing group"
    )


def test_constraint_stress_fails_closed_with_the_accepted_typed_error() -> None:
    """The accepted implementation has no global minimum-deviation fallback.

    This is the FD-B2-7 Fixture B capability gap.  A passing test means the
    harness detected and classified the gap correctly; it does NOT mean the
    production behaviour satisfies FD-B2-7, and no production correction is
    authorized or made here.
    """
    with pytest.raises(SplitAllocationError) as caught:
        FixtureSplitFacade.run(build_request(fx.CONSTRAINT_STRESS_FIXTURE_ID))
    assert str(caught.value) == CONSTRAINT_STRESS_ALLOCATION_MESSAGE, (
        "the typed boundary-crossing failure message drifted from its frozen literal"
    )


def test_constraint_stress_typed_failure_is_not_conformance() -> None:
    criterion = criterion_by_key("indivisible-group-minimum-deviation")
    assert criterion.status == UNSATISFIED, (
        "the minimum-deviation criterion must be recorded UNSATISFIED, never SATISFIED"
    )
    assert criterion.status != SATISFIED
    assert criterion.status != NOT_APPLICABLE


def test_constraint_stress_has_zero_source_document_group_overlap() -> None:
    plan = fx.build_plan(fx.CONSTRAINT_STRESS_FIXTURE_ID)
    documents = [group.source_document_id for group in plan.groups]
    assert len(set(documents)) == len(documents), (
        "no source document may appear in more than one constraint-stress group"
    )


def test_constraint_stress_nominal_partition_totals_remain_seven_hundred_and_two_fifties() -> None:
    inputs = fx.fixture_inputs(fx.CONSTRAINT_STRESS_FIXTURE_ID)
    assert dict(inputs.partition_totals) == {"train": 700, "validation": 150, "test": 150}


# ===========================================================================
# 4. leakage-positive-v1 (FD-B2D-6)
# ===========================================================================


def test_leakage_positive_has_nine_hundred_and_ninety_nine_groups() -> None:
    plan = fx.build_plan(fx.LEAKAGE_POSITIVE_FIXTURE_ID)
    assert plan.group_count == 999, "leakage-positive-v1 must have exactly 999 groups"


def test_leakage_positive_has_one_pair_and_nine_hundred_and_ninety_eight_singletons() -> None:
    plan = fx.build_plan(fx.LEAKAGE_POSITIVE_FIXTURE_ID)
    histogram = dict(Counter(plan.group_sizes()))
    assert histogram == {1: 998, 2: 1}, (
        f"leakage-positive must be 998 singletons and exactly one pair, got {histogram}"
    )


def test_leakage_positive_pair_is_homogeneous_and_frozen() -> None:
    plan = fx.build_plan(fx.LEAKAGE_POSITIVE_FIXTURE_ID)
    pairs = [group for group in plan.groups if group.size == 2]
    assert len(pairs) == 1, "there must be exactly one multi-example group"
    pair = pairs[0]
    assert pair.source_document_id == fx.PAIR_SOURCE_DOCUMENT_ID, (
        "the two-example group's document identifier drifted from its frozen literal"
    )
    assert pair.decision == fx.PAIR_DECISION, "both pair examples must share one decision"
    assert pair.row_ordinals == fx.PAIR_ROW_ORDINALS, "the pair row ordinals drifted"


def test_leakage_positive_pair_never_straddles_a_partition_boundary(
    leakage_positive_result: FixtureSplitResult,
) -> None:
    assignments = {
        record.example_id: record.split
        for record in leakage_positive_result.split_manifest.split_assignments
    }
    partitions = {assignments[example_id] for example_id in fx.PAIR_EXAMPLE_IDS}
    assert partitions == {fx.PAIR_PARTITION}, (
        f"the two-example group must remain wholly inside {fx.PAIR_PARTITION!r}, got {partitions}"
    )


def test_leakage_positive_pair_sits_strictly_inside_its_partition_run() -> None:
    plan = fx.build_plan(fx.LEAKAGE_POSITIVE_FIXTURE_ID)
    groups = plan.groups_for(fx.PAIR_DECISION)
    ranks = [
        index
        for index, group in enumerate(groups)
        if group.source_document_id == fx.PAIR_SOURCE_DOCUMENT_ID
    ]
    assert ranks == [fx.PAIR_D6_RANK], f"the pair must sit at D6 rank {fx.PAIR_D6_RANK}"
    train_total = fx.RATIFIED_MATRIX[fx.PAIR_DECISION]["train"]
    assert fx.PAIR_D6_RANK > 0, "the pair must not touch the start of its partition run"
    assert train_total > fx.PAIR_D6_RANK + 2, "the pair must not touch the end of its partition run"


def test_leakage_positive_pair_candidate_is_the_lowest_indexed_valid_candidate() -> None:
    assert fx.PAIR_CANDIDATE_ORDINAL == 0, "the pair candidate ordinal drifted"
    derived = fx.source_document_id(
        fx.LEAKAGE_POSITIVE_FIXTURE_ID, fx.PAIR_DECISION, fx.PAIR_CANDIDATE_ORDINAL
    )
    assert derived == fx.PAIR_SOURCE_DOCUMENT_ID, (
        "the frozen pair document must be the frozen candidate ordinal's document"
    )


def test_leakage_positive_group_counts_by_decision() -> None:
    plan = fx.build_plan(fx.LEAKAGE_POSITIVE_FIXTURE_ID)
    counts = {decision: len(plan.groups_for(decision)) for decision in fx.DECISIONS}
    assert counts == {"yes": 551, "no": 338, "maybe": 110}, (
        f"leakage-positive group counts must be yes 551 / no 338 / maybe 110, got {counts}"
    )


def test_leakage_positive_covers_exactly_nine_scenarios() -> None:
    assert len(fx.LEAKAGE_SCENARIOS) == 9, "exactly nine deterministic scenarios are required"
    assert tuple(scenario.index for scenario in fx.LEAKAGE_SCENARIOS) == tuple(range(1, 10))
    assert len({scenario.slug for scenario in fx.LEAKAGE_SCENARIOS}) == 9, (
        "every scenario slug must be distinct"
    )


def test_scenario_finding_types_are_frozen() -> None:
    observed = tuple(scenario.finding_type for scenario in fx.LEAKAGE_SCENARIOS)
    assert observed == SCENARIO_FINDING_TYPES, "scenario finding types drifted"


def test_scenario_score_representations_are_frozen() -> None:
    observed = tuple(scenario.score_representation for scenario in fx.LEAKAGE_SCENARIOS)
    assert observed == SCENARIO_SCORE_REPRESENTATIONS, "scenario score representations drifted"


def test_scenario_classifications_are_frozen() -> None:
    observed = tuple(scenario.classification for scenario in fx.LEAKAGE_SCENARIOS)
    assert observed == SCENARIO_CLASSIFICATIONS, "scenario classifications drifted"


def test_scenario_evidence_reference_outcomes_are_frozen() -> None:
    observed = tuple(scenario.evidence_reference_outcome for scenario in fx.LEAKAGE_SCENARIOS)
    assert observed == SCENARIO_EVIDENCE_OUTCOMES, "scenario evidence-reference outcomes drifted"


def test_every_false_positive_carries_a_stable_non_path_evidence_reference() -> None:
    for scenario in fx.LEAKAGE_SCENARIOS:
        if scenario.classification != "false_positive":
            continue
        reference = scenario.evidence_reference
        assert reference is not None, (
            f"scenario {scenario.index} is a false positive and must carry an evidence reference"
        )
        assert reference.startswith("mesc-pilot-01-b2d-leakage-scenario/1/"), (
            f"scenario {scenario.index} evidence reference must use the ratified namespace"
        )
        assert reference.strip() == reference, "an evidence reference must be stripped"
        assert "\\" not in reference, "an evidence reference must never be a local path"
        assert not reference.startswith(("/", "./", "../", "~")), (
            "an evidence reference must never be a local path"
        )


def test_scenario_one_exact_example_identity_is_a_same_partition_control() -> None:
    scenario = fx.LEAKAGE_SCENARIOS[0]
    assert scenario.index in SAME_PARTITION_CONTROL_INDICES
    assert scenario.partitions == ("train",), (
        "the exact-example self-identity control must name exactly one actual partition"
    )
    assert len(scenario.example_ids) == 1, "the self-identity control uses one actual example"
    assert exact_example_identity(scenario.example_ids[0], scenario.example_ids[0]) is True


def test_scenario_two_source_document_identity_is_a_same_partition_control() -> None:
    scenario = fx.LEAKAGE_SCENARIOS[1]
    assert scenario.index in SAME_PARTITION_CONTROL_INDICES
    assert scenario.partitions == ("train",), (
        "the source-document control must name exactly one actual partition"
    )
    assert scenario.source_document_ids == (fx.PAIR_SOURCE_DOCUMENT_ID,)
    assert len(scenario.example_ids) == 2, "the control uses the actual two-example group"
    assert exact_source_document_identity(fx.PAIR_SOURCE_DOCUMENT_ID, fx.PAIR_SOURCE_DOCUMENT_ID)


def test_same_partition_controls_are_never_cross_partition_findings() -> None:
    for index in SAME_PARTITION_CONTROL_INDICES:
        scenario = fx.LEAKAGE_SCENARIOS[index - 1]
        assert len(scenario.partitions) == 1, (
            f"scenario {index} is a same-partition synthetic control and must never be "
            "represented as cross-partition leakage, duplicate split membership or "
            "source-document overlap"
        )


def test_scenario_frozen_identities_are_actual_fixture_membership(
    leakage_positive_result: FixtureSplitResult,
) -> None:
    """No fabricated partition claim: every frozen identity is real fixture membership."""
    assignments = {
        record.example_id: record.split
        for record in leakage_positive_result.split_manifest.split_assignments
    }
    documents = {
        record.example_id: record.source_document_id
        for record in leakage_positive_result.split_manifest.split_assignments
    }
    for scenario in fx.LEAKAGE_SCENARIOS:
        for example_id in scenario.example_ids:
            assert example_id in assignments, (
                f"scenario {scenario.index} names {example_id!r}, which is not an actual example"
            )
        observed = tuple(sorted({assignments[e] for e in scenario.example_ids}))
        assert observed == scenario.partitions, (
            f"scenario {scenario.index} frozen partitions {scenario.partitions} do not match "
            f"the actual membership {observed}"
        )
        observed_documents = tuple(sorted({documents[e] for e in scenario.example_ids}))
        assert observed_documents == scenario.source_document_ids, (
            f"scenario {scenario.index} frozen source documents do not match actual membership"
        )


def test_scenario_three_exact_question_equality() -> None:
    scenario = fx.LEAKAGE_SCENARIOS[2]
    assert exact_question_equality(scenario.left_surface, scenario.right_surface) is True


def test_scenario_four_normalized_question_equality() -> None:
    scenario = fx.LEAKAGE_SCENARIOS[3]
    assert exact_question_equality(scenario.left_surface, scenario.right_surface) is False, (
        "the normalized-question scenario must not be byte-equal"
    )
    assert normalized_question_equality(scenario.left_surface, scenario.right_surface) is True
    assert normalize_question(scenario.left_surface) == scenario.right_surface


def test_scenario_four_left_surface_has_the_exact_frozen_byte_composition() -> None:
    surface = fx.SCENARIO_FOUR_LEFT
    assert surface.startswith("  "), "exactly two leading ASCII spaces"
    assert surface.endswith("  "), "exactly two trailing ASCII spaces"
    assert surface.count("\u00a0") == 1, "exactly one U+00A0 between Does and ALPHA"
    assert "Does\u00a0ALPHA" in surface, "the NO-BREAK SPACE sits between Does and ALPHA"
    assert "\t" not in surface and "\n" not in surface, "no tab and no line feed"


def test_scenario_five_question_jaccard_is_exactly_at_threshold() -> None:
    scenario = fx.LEAKAGE_SCENARIOS[4]
    outcome = token_set_jaccard(
        question_token_set(scenario.left_surface), question_token_set(scenario.right_surface)
    )
    assert (outcome.intersection_size, outcome.union_size) == (9, 10)
    assert outcome.score_representation == "jaccard:9/10"
    assert outcome.near_duplicate_threshold_passed is True
    assert 100 * outcome.intersection_size == NEAR_DUPLICATE_THRESHOLD_PERCENT * outcome.union_size


def test_scenario_six_question_jaccard_is_above_threshold() -> None:
    scenario = fx.LEAKAGE_SCENARIOS[5]
    outcome = token_set_jaccard(
        question_token_set(scenario.left_surface), question_token_set(scenario.right_surface)
    )
    assert (outcome.intersection_size, outcome.union_size) == (10, 11)
    assert outcome.score_representation == "jaccard:10/11"
    assert outcome.near_duplicate_threshold_passed is True
    assert 100 * outcome.intersection_size > NEAR_DUPLICATE_THRESHOLD_PERCENT * outcome.union_size


def test_scenario_seven_exact_context_equality() -> None:
    scenario = fx.LEAKAGE_SCENARIOS[6]
    assert exact_context_equality(scenario.left_surface, scenario.right_surface) is True


def test_scenario_eight_approximate_context_overlap_is_exactly_at_threshold() -> None:
    scenario = fx.LEAKAGE_SCENARIOS[7]
    outcome = token_set_jaccard(
        question_token_set(scenario.left_surface), question_token_set(scenario.right_surface)
    )
    assert (outcome.intersection_size, outcome.union_size) == (19, 20)
    assert outcome.score_representation == "jaccard:19/20"
    assert outcome.context_overlap_threshold_passed is True
    assert 100 * outcome.intersection_size == CONTEXT_OVERLAP_THRESHOLD_PERCENT * outcome.union_size


def test_scenario_nine_both_questions_normalize_to_empty() -> None:
    scenario = fx.LEAKAGE_SCENARIOS[8]
    assert normalize_question(scenario.left_surface) == ""
    assert normalize_question(scenario.right_surface) == ""
    assert is_empty_normalized_question_pair(scenario.left_surface, scenario.right_surface) is True
    assert scenario.score_representation == "not_evaluable"


def test_scenario_nine_surfaces_have_the_exact_frozen_code_points() -> None:
    assert fx.SCENARIO_NINE_LEFT == "\u0020\u0009\u000a", (
        "scenario 9 left must be ASCII space, horizontal tab, line feed"
    )
    assert fx.SCENARIO_NINE_RIGHT == "\u2003\u00a0", (
        "scenario 9 right must be EM SPACE, NO-BREAK SPACE"
    )


def test_leakage_audit_aggregate_is_frozen(leakage_positive_result: FixtureSplitResult) -> None:
    report = leakage_positive_result.audit_report
    assert report.finding_count == 9, "the audit must carry exactly nine findings"
    assert report.leaked is True, "leaked must be true because unresolved findings exist"
    classifications = Counter(finding.classification for finding in report.findings)
    assert classifications["false_positive"] == FALSE_POSITIVE_COUNT, (
        f"exactly {FALSE_POSITIVE_COUNT} supported false positives are required"
    )
    assert classifications["unresolved"] == UNRESOLVED_COUNT, (
        f"exactly {UNRESOLVED_COUNT} unresolved findings are required"
    )
    assert classifications["confirmed_leakage"] == 0, "no confirmed leakage is synthesized"
    suppressed = [finding for finding in report.findings if finding.suppressed]
    assert len(suppressed) == SUPPRESSED_COUNT, "suppression is prohibited"


def test_ordered_finding_ids_match_their_frozen_literals(
    leakage_positive_result: FixtureSplitResult,
) -> None:
    observed = tuple(
        finding.finding_id for finding in leakage_positive_result.audit_report.findings
    )
    assert observed == LEAKAGE_POSITIVE_GOLDEN.ordered_finding_ids, (
        "the ordered finding identifiers drifted from their frozen literals"
    )
    assert list(observed) == sorted(observed), (
        "findings must be ordered by strictly ascending finding_id"
    )


def test_audit_report_records_the_ratified_detection_methods(
    leakage_positive_result: FixtureSplitResult,
) -> None:
    assert leakage_positive_result.audit_report.detection_methods == fx.DETECTION_METHODS


# ===========================================================================
# 5. Frozen golden byte surfaces (FD-B2D-7)
# ===========================================================================


@pytest.mark.parametrize("fixture_id", SUCCESSFUL_FIXTURE_IDS)
def test_request_identity_regenerates_from_the_frozen_literals(
    fixture_id: str, results: dict[str, FixtureSplitResult]
) -> None:
    """The facade recomputes both digests and refuses a mismatch, so a passing
    run proves the frozen ``fixture_sha256`` and ``request_id`` are the real ones.
    """
    golden = GOLDENS[fixture_id]
    assert results[fixture_id].request_id == golden.request_id
    assert golden.request_id.startswith(REQUEST_ID_PREFIX)
    assert len(golden.fixture_sha256) == 64


@pytest.mark.parametrize("fixture_id", SUCCESSFUL_FIXTURE_IDS)
def test_split_hash_matches_its_frozen_literal(
    fixture_id: str, results: dict[str, FixtureSplitResult]
) -> None:
    golden = GOLDENS[fixture_id]
    observed = results[fixture_id].split_manifest.computed_split_hash
    assert observed == golden.split_hash, (
        f"{fixture_id} compatibility split_hash drifted from its frozen literal"
    )
    assert len(observed) == 16, "the compatibility split_hash must be 16 hex characters"


@pytest.mark.parametrize("fixture_id", SUCCESSFUL_FIXTURE_IDS)
def test_split_fingerprint_matches_its_frozen_literal(
    fixture_id: str, results: dict[str, FixtureSplitResult]
) -> None:
    golden = GOLDENS[fixture_id]
    observed = results[fixture_id].split_fingerprint_record.split_fingerprint
    assert observed == golden.split_fingerprint, (
        f"{fixture_id} authoritative split_fingerprint drifted from its frozen literal"
    )
    assert len(observed) == 64, "the authoritative fingerprint must be 64 hex characters"


@pytest.mark.parametrize("fixture_id", SUCCESSFUL_FIXTURE_IDS)
def test_every_canonical_byte_surface_matches_its_frozen_digest_and_size(
    fixture_id: str, results: dict[str, FixtureSplitResult]
) -> None:
    golden = GOLDENS[fixture_id]
    expected = {
        "group_registry": (golden.group_registry_sha256, golden.group_registry_byte_size),
        "example_registry": (golden.example_registry_sha256, golden.example_registry_byte_size),
        "excluded_ledger": (golden.excluded_ledger_sha256, golden.excluded_ledger_byte_size),
        "split_summary_identity_core": (
            golden.summary_core_sha256,
            golden.summary_core_byte_size,
        ),
        "split_summary_document": (
            golden.summary_document_sha256,
            golden.summary_document_byte_size,
        ),
        "leakage_audit_report": (golden.audit_report_sha256, golden.audit_report_byte_size),
    }
    surfaces = byte_surfaces(results[fixture_id])
    for role, (digest, size) in expected.items():
        payload = surfaces[role]
        assert sha256_of_bytes(payload) == digest, (
            f"{fixture_id} {role} digest drifted from its frozen literal"
        )
        assert len(payload) == size, (
            f"{fixture_id} {role} byte size is {len(payload)}, expected {size}"
        )


@pytest.mark.parametrize("fixture_id", SUCCESSFUL_FIXTURE_IDS)
def test_artifact_descriptors_agree_with_the_frozen_digests_and_sizes(
    fixture_id: str, results: dict[str, FixtureSplitResult]
) -> None:
    golden = GOLDENS[fixture_id]
    expected = {
        "group_registry": (golden.group_registry_sha256, golden.group_registry_byte_size),
        "example_registry": (golden.example_registry_sha256, golden.example_registry_byte_size),
        "excluded_ledger": (golden.excluded_ledger_sha256, golden.excluded_ledger_byte_size),
        "split_summary": (golden.summary_core_sha256, golden.summary_core_byte_size),
    }
    descriptors = results[fixture_id].split_fingerprint_record.identity.artifact_descriptors
    assert sorted(descriptor.role for descriptor in descriptors) == sorted(expected)
    for descriptor in descriptors:
        digest, size = expected[descriptor.role]
        assert descriptor.sha256 == digest, f"{fixture_id} {descriptor.role} descriptor digest"
        assert descriptor.byte_size == size, f"{fixture_id} {descriptor.role} descriptor size"


@pytest.mark.parametrize("fixture_id", SUCCESSFUL_FIXTURE_IDS)
def test_summary_counts_match_their_frozen_literals(
    fixture_id: str, results: dict[str, FixtureSplitResult]
) -> None:
    golden = GOLDENS[fixture_id]
    core = results[fixture_id].split_summary_identity_core
    assert core.total_example_count == golden.record_count, f"{fixture_id} record count"
    assert core.total_group_count == golden.group_count, f"{fixture_id} group count"
    assert core.excluded_record_count == golden.excluded_count, f"{fixture_id} excluded count"
    assert dict(core.partition_totals) == dict(golden.partition_counts), (
        f"{fixture_id} partition counts"
    )
    assert dict(core.group_counts_by_partition) == dict(golden.group_counts_by_partition), (
        f"{fixture_id} group counts by partition"
    )
    observed_matrix = {
        partition: dict(row) for partition, row in core.partition_label_matrix.items()
    }
    assert observed_matrix == {
        partition: dict(row) for partition, row in golden.label_matrix.items()
    }, f"{fixture_id} label matrix drifted from the ratified matrix"
    assert dict(core.label_totals) == {"yes": 552, "no": 338, "maybe": 110}


@pytest.mark.parametrize("fixture_id", SUCCESSFUL_FIXTURE_IDS)
def test_audit_aggregates_match_their_frozen_literals(
    fixture_id: str, results: dict[str, FixtureSplitResult]
) -> None:
    golden = GOLDENS[fixture_id]
    report = results[fixture_id].audit_report
    assert report.finding_count == golden.finding_count, f"{fixture_id} finding count"
    assert report.leaked is golden.leaked, f"{fixture_id} leaked value"
    assert tuple(finding.finding_id for finding in report.findings) == golden.ordered_finding_ids


@pytest.mark.parametrize("fixture_id", SUCCESSFUL_FIXTURE_IDS)
def test_no_group_crosses_a_partition_in_the_facade_result(
    fixture_id: str, results: dict[str, FixtureSplitResult]
) -> None:
    partition_by_document: dict[str, str] = {}
    for record in results[fixture_id].split_manifest.split_assignments:
        existing = partition_by_document.setdefault(record.source_document_id, record.split)
        assert existing == record.split, (
            f"{fixture_id} source document {record.source_document_id!r} crosses partitions"
        )


@pytest.mark.parametrize("fixture_id", SUCCESSFUL_FIXTURE_IDS)
def test_no_duplicate_example_id_or_row_ordinal(
    fixture_id: str, results: dict[str, FixtureSplitResult]
) -> None:
    assignments = results[fixture_id].split_manifest.split_assignments
    example_ids = [record.example_id for record in assignments]
    assert len(set(example_ids)) == len(example_ids) == 1000, (
        f"{fixture_id} must assign exactly 1000 distinct example identifiers"
    )
    ordinals = [row.row_ordinal for row in fx.build_plan(fixture_id).ordered_rows]
    assert len(set(ordinals)) == len(ordinals) == 1000, f"{fixture_id} row ordinals must be unique"


# ===========================================================================
# 6. Determinism (FD-B2D-8, criterion 9)
# ===========================================================================


@pytest.mark.parametrize("fixture_id", SUCCESSFUL_FIXTURE_IDS)
def test_repeated_runs_are_byte_identical(fixture_id: str) -> None:
    first = byte_surfaces(FixtureSplitFacade.run(build_request(fixture_id)))
    second = byte_surfaces(FixtureSplitFacade.run(build_request(fixture_id)))
    assert first == second, f"{fixture_id} byte surfaces must be identical across runs"


def test_fixture_construction_is_deterministic() -> None:
    for fixture_id in fx.FIXTURE_IDS:
        first = fx.build_plan(fixture_id)
        fx.build_plan.cache_clear()
        fx.ranked_candidates.cache_clear()
        second = fx.build_plan(fixture_id)
        assert first.ordered_rows == second.ordered_rows, f"{fixture_id} rows must be stable"
        assert first.source_labels == second.source_labels, f"{fixture_id} labels must be stable"
        assert first.groups == second.groups, f"{fixture_id} groups must be stable"


def test_identity_values_are_stable_in_a_fresh_process() -> None:
    """Cross-process stability under a different hash seed (FD-B2D-8)."""
    environment = dict(os.environ)
    environment["PYTHONHASHSEED"] = "1"
    environment.pop("PYTHONDONTWRITEBYTECODE", None)
    completed = subprocess.run(
        [
            sys.executable,
            "-c",
            "import sys;sys.path.insert(0, sys.argv[1]);"
            "import test_mesc_p01_04b2d_qualification_v1 as q;"
            "sys.stdout.write(q.cross_process_digest_report())",
            str(Path(__file__).resolve().parent),
        ],
        capture_output=True,
        text=True,
        check=False,
        env=environment,
    )
    assert completed.returncode == 0, (
        f"the cross-process qualification run failed: {completed.stderr}"
    )
    assert completed.stdout == cross_process_digest_report(), (
        "identity values differ between processes"
    )


def test_cross_process_report_matches_the_frozen_literals() -> None:
    report = digest_report()
    for fixture_id in SUCCESSFUL_FIXTURE_IDS:
        golden = GOLDENS[fixture_id]
        observed = report[fixture_id]
        assert isinstance(observed, dict)
        assert observed["split_fingerprint"] == golden.split_fingerprint
        assert observed["split_hash"] == golden.split_hash
        assert observed["request_id"] == golden.request_id
        assert observed["synthetic_identity_proof"] == golden.synthetic_identity_proof
    stress = report[fx.CONSTRAINT_STRESS_FIXTURE_ID]
    assert isinstance(stress, dict)
    assert stress["error_type"] == "SplitAllocationError"
    assert stress["error_message"] == CONSTRAINT_STRESS_ALLOCATION_MESSAGE


# ===========================================================================
# 7. Raw-text exclusion and date-free byte surfaces (FD-B2D-6 §8.5, FD-B2D-9)
# ===========================================================================


def test_no_raw_synthetic_text_reaches_any_canonical_byte_surface(
    leakage_positive_result: FixtureSplitResult,
) -> None:
    violations: list[tuple[str, str]] = []
    for role, payload in byte_surfaces(leakage_positive_result).items():
        for probe in fx.RAW_SURFACE_PROBES:
            if probe.encode("utf-8") in payload:
                violations.append((role, probe))
    assert not violations, f"raw synthetic surface text reached a promotable surface: {violations}"


def test_findings_carry_only_allowlisted_shared_surface_markers(
    leakage_positive_result: FixtureSplitResult,
) -> None:
    allowed = {
        "context_bytes",
        "context_token_set",
        "empty_normalized_question",
        "example_id",
        "normalized_question",
        "question_bytes",
        "question_token_set",
        "source_document_id",
    }
    for finding in leakage_positive_result.audit_report.findings:
        assert set(finding.shared_surface) <= allowed, (
            f"finding {finding.finding_id} carries a non-allowlisted shared surface marker"
        )


def test_finding_ids_carry_no_raw_text(leakage_positive_result: FixtureSplitResult) -> None:
    for finding in leakage_positive_result.audit_report.findings:
        for probe in fx.RAW_SURFACE_PROBES:
            assert probe not in finding.finding_id, (
                f"finding identifier {finding.finding_id} leaks raw surface text"
            )


# ===========================================================================
# 8. Fail-closed behaviour (FD-B2D-11, contract §5.4)
# ===========================================================================


def test_mismatched_fixture_digest_fails_closed() -> None:
    with pytest.raises(FixtureIdentityMismatchError):
        FixtureSplitFacade.run(
            build_request(
                fx.EXACT_REFERENCE_FIXTURE_ID, fixture_sha256=CONSTRAINT_STRESS_FIXTURE_SHA256
            )
        )


def test_mismatched_request_id_fails_closed() -> None:
    with pytest.raises(FixtureIdentityMismatchError):
        FixtureSplitFacade.run(
            build_request(fx.EXACT_REFERENCE_FIXTURE_ID, request_id=CONSTRAINT_STRESS_REQUEST_ID)
        )


def test_a_request_that_does_not_declare_fixture_only_fails_closed() -> None:
    with pytest.raises(FixtureOnlyModeError):
        build_request(fx.EXACT_REFERENCE_FIXTURE_ID, fixture_only=False)


def test_a_request_that_does_not_declare_non_evidence_fails_closed() -> None:
    with pytest.raises(FixtureOnlyModeError):
        build_request(fx.EXACT_REFERENCE_FIXTURE_ID, non_evidence=False)


def test_a_namespace_that_is_not_derived_from_the_fixture_id_fails_closed() -> None:
    with pytest.raises(InvalidFixtureRequestError):
        build_request(
            fx.EXACT_REFERENCE_FIXTURE_ID, fixture_namespace="mesc-fixture/p01-04b2/1/other"
        )


def test_partition_totals_that_do_not_sum_to_the_row_count_fail_closed() -> None:
    with pytest.raises(InvalidFixtureRequestError):
        build_request(
            fx.EXACT_REFERENCE_FIXTURE_ID,
            partition_totals={"train": 700, "validation": 150, "test": 149},
        )


def test_a_derived_group_that_would_cross_one_exact_boundary_fails_closed() -> None:
    """Derived negative mutation — never a qualification fixture (contract §5.4)."""
    plan = fx.build_plan(fx.EXACT_REFERENCE_FIXTURE_ID)
    yes_groups = plan.groups_for("yes")
    donor = yes_groups[30]
    receiver = yes_groups[31]
    assert donor.size == 1 and receiver.size == 13, "the mutation targets the frozen ranked layout"
    moved = set(donor.row_ordinals)
    rows = tuple(
        row
        if row.row_ordinal not in moved
        else type(row)(
            original_example_id=row.original_example_id,
            row_ordinal=row.row_ordinal,
            source_document_id=receiver.source_document_id,
        )
        for row in plan.ordered_rows
    )
    labels = tuple(
        label
        if label.original_example_id
        not in {fx.original_example_id(plan.fixture_id, ordinal) for ordinal in moved}
        else type(label)(
            dataset_id=label.dataset_id,
            dataset_revision=label.dataset_revision,
            configuration=label.configuration,
            original_example_id=label.original_example_id,
            source_document_id=receiver.source_document_id,
            decision=label.decision,
            source_record_hash=label.source_record_hash,
        )
        for label in plan.source_labels
    )
    joined = join_labels(rows, labels, transformation_version=fx.TRANSFORMATION_VERSION)
    targets = constrained_apportionment(
        {"yes": 552, "no": 338, "maybe": 110},
        {"train": 700, "validation": 150, "test": 150},
    )
    with pytest.raises(SplitAllocationError):
        allocate_indivisible_groups(joined, targets)


def test_a_source_document_group_crossing_decision_strata_fails_closed() -> None:
    """Derived negative mutation — never a qualification fixture (contract §5.4)."""
    plan = fx.build_plan(fx.EXACT_REFERENCE_FIXTURE_ID)
    target_document = plan.groups_for("yes")[0].source_document_id
    flipped = False
    labels: list[Any] = []
    for label in plan.source_labels:
        if label.source_document_id == target_document and not flipped:
            labels.append(
                type(label)(
                    dataset_id=label.dataset_id,
                    dataset_revision=label.dataset_revision,
                    configuration=label.configuration,
                    original_example_id=label.original_example_id,
                    source_document_id=label.source_document_id,
                    decision="no",
                    source_record_hash=label.source_record_hash,
                )
            )
            flipped = True
        else:
            labels.append(label)
    assert flipped, "the mutation must flip exactly one decision"
    joined = join_labels(
        plan.ordered_rows, tuple(labels), transformation_version=fx.TRANSFORMATION_VERSION
    )
    targets = constrained_apportionment(
        {"yes": 551, "no": 339, "maybe": 110},
        {"train": 700, "validation": 150, "test": 150},
    )
    with pytest.raises(SplitInputError):
        allocate_indivisible_groups(joined, targets)


def test_a_registry_and_label_source_document_mismatch_fails_closed() -> None:
    plan = fx.build_plan(fx.EXACT_REFERENCE_FIXTURE_ID)
    labels = list(plan.source_labels)
    first = labels[0]
    labels[0] = type(first)(
        dataset_id=first.dataset_id,
        dataset_revision=first.dataset_revision,
        configuration=first.configuration,
        original_example_id=first.original_example_id,
        source_document_id="mesc-b2d-exact-reference-1000-v1-yes-doc-9999",
        decision=first.decision,
        source_record_hash=first.source_record_hash,
    )
    with pytest.raises(SplitInputError):
        join_labels(
            plan.ordered_rows, tuple(labels), transformation_version=fx.TRANSFORMATION_VERSION
        )


def test_derived_mutations_receive_no_fixture_identity() -> None:
    """A derived negative mutation is never an approved qualification fixture."""
    assert "mutation" not in " ".join(fx.FIXTURE_IDS)
    assert len(fx.FIXTURE_IDS) == 3
    assert set(_IDENTITIES) == set(fx.FIXTURE_IDS), (
        "only the three ratified fixtures may carry a fixture identity digest"
    )


# ===========================================================================
# 9. The thirteen-criterion P01-04B mapping (FD-B2D-9)
# ===========================================================================


def criterion_by_key(key: str) -> Criterion:
    """Return the mapped criterion with the given key."""
    matches = [criterion for criterion in P01_04B_CRITERIA if criterion.key == key]
    assert len(matches) == 1, f"exactly one criterion must carry the key {key!r}"
    return matches[0]


def test_criterion_01_public_splitter_remains_fail_closed() -> None:
    splitter = SourceDocumentGroupedSplitter()
    with pytest.raises(PilotSplitNotAuthorizedError):
        splitter.assign([], [])
    with pytest.raises(PilotSplitNotAuthorizedError):
        splitter.assign(["a"], ["d"])
    assert criterion_by_key("public-splitter-fail-closed").status == SATISFIED


def test_criterion_02_separate_fixture_only_facade() -> None:
    assert not issubclass(FixtureSplitFacade, SourceDocumentGroupedSplitter), (
        "the fixture facade must be separate from the fail-closed public splitter"
    )
    assert FixtureSplitFacade.__module__ == "medscale.mesc._fixture_split_v1"
    assert SourceDocumentGroupedSplitter.__module__ == "medscale.mesc.split"
    assert hasattr(FixtureSplitFacade, "run")
    assert "FixtureSplitFacade" not in mesc_package.__all__, (
        "the fixture facade must stay private and unexported"
    )
    with pytest.raises(FixtureOnlyModeError):
        build_request(fx.EXACT_REFERENCE_FIXTURE_ID, fixture_only=False)
    assert criterion_by_key("separate-fixture-facade").status == SATISFIED


def test_criterion_03_library_only_in_memory_path(monkeypatch: pytest.MonkeyPatch) -> None:
    def refuse(*args: object, **kwargs: object) -> object:
        raise AssertionError("the qualification path must perform no I/O")

    monkeypatch.setattr(builtins, "open", refuse)
    monkeypatch.setattr(socket, "socket", refuse)
    monkeypatch.setattr(subprocess, "Popen", refuse)
    monkeypatch.setattr(Path, "open", refuse)
    result = FixtureSplitFacade.run(build_request(fx.EXACT_REFERENCE_FIXTURE_ID))
    assert isinstance(result.group_registry_bytes, bytes)
    assert result.split_fingerprint_record.split_fingerprint == (
        EXACT_REFERENCE_GOLDEN.split_fingerprint
    )
    assert criterion_by_key("library-only-in-memory").status == SATISFIED


def test_criterion_04_no_b2_cli_exists() -> None:
    cli = Path(__file__).resolve().parent.parent / "src" / "medscale" / "cli"
    offenders = [
        path.name
        for path in sorted(cli.glob("*.py"))
        if "_fixture_split_v1" in path.read_text(encoding="utf-8")
        or "FixtureSplitFacade" in path.read_text(encoding="utf-8")
    ]
    assert not offenders, f"no CLI module may reference the B2 fixture facade: {offenders}"
    assert not any("fixture" in name.lower() for name in mesc_package.__all__)
    assert criterion_by_key("no-b2-cli").status == SATISFIED


def test_criterion_05_split_fingerprint_is_authoritative(
    results: dict[str, FixtureSplitResult],
) -> None:
    fingerprints = set()
    for fixture_id in SUCCESSFUL_FIXTURE_IDS:
        result = results[fixture_id]
        fingerprint = result.split_fingerprint_record.split_fingerprint
        assert len(fingerprint) == 64 and set(fingerprint) <= set("0123456789abcdef")
        assert fingerprint == GOLDENS[fixture_id].split_fingerprint
        assert fingerprint.encode("utf-8") in result.split_summary_document_bytes, (
            "the final summary must carry the authoritative fingerprint"
        )
        fingerprints.add(fingerprint)
    assert len(fingerprints) == 2, "different identity cores must produce different fingerprints"
    assert criterion_by_key("authoritative-fingerprint").status == SATISFIED


def test_criterion_06_split_hash_is_compatibility_only(
    results: dict[str, FixtureSplitResult],
) -> None:
    for fixture_id in SUCCESSFUL_FIXTURE_IDS:
        result = results[fixture_id]
        split_hash = result.split_manifest.computed_split_hash
        assert len(split_hash) == 16, "the compatibility hash must be 16 hex characters"
        identity_bytes = result.split_fingerprint_record.identity.canonical_bytes()
        assert split_hash.encode("utf-8") not in identity_bytes, (
            "the compatibility split_hash must never enter the fingerprinted payload"
        )
    assert criterion_by_key("compatibility-split-hash").status == SATISFIED


def test_criterion_07_leakage_normalization_follows_fd_b2_6(
    leakage_positive_result: FixtureSplitResult,
) -> None:
    assert dict(NORMALIZATION_RECORD) == {
        "case_folding": "unicode_case_folding",
        "unicode_normalization": "NFKC",
        "whitespace_collapse": "unicode_whitespace_runs_to_single_ascii_space",
        "whitespace_trim": "strip_leading_and_trailing_whitespace",
    }, "the recorded normalization pipeline drifted from FD-B2-6"
    document = leakage_positive_result.audit_report.to_canonical_document()
    assert document["normalization_record"] == dict(NORMALIZATION_RECORD)
    assert NEAR_DUPLICATE_THRESHOLD_PERCENT == 90
    assert CONTEXT_OVERLAP_THRESHOLD_PERCENT == 95
    assert criterion_by_key("fd-b2-6-normalization").status == SATISFIED


def test_criterion_08_exactly_three_named_fixtures() -> None:
    assert fx.FIXTURE_IDS == (
        "exact-reference-1000-v1",
        "constraint-stress-1000-v1",
        "leakage-positive-v1",
    )
    assert criterion_by_key("three-named-fixtures").status == SATISFIED


def test_criterion_09_stable_inputs_are_byte_identical(
    results: dict[str, FixtureSplitResult],
) -> None:
    for fixture_id in SUCCESSFUL_FIXTURE_IDS:
        repeated = FixtureSplitFacade.run(build_request(fixture_id))
        assert byte_surfaces(repeated) == byte_surfaces(results[fixture_id])
    assert criterion_by_key("byte-identical-results").status == SATISFIED


def test_criterion_10_no_real_p01_03g_membership(results: dict[str, FixtureSplitResult]) -> None:
    for fixture_id in SUCCESSFUL_FIXTURE_IDS:
        for role, payload in byte_surfaces(results[fixture_id]).items():
            assert b"pqa" not in payload, f"{fixture_id} {role} must not name a real configuration"
            assert b"pubmedqa" not in payload.lower(), (
                f"{fixture_id} {role} must not name the real dataset"
            )
            assert b"source-records.jsonl" not in payload, (
                f"{fixture_id} {role} must not reference a real registry file"
            )
    plan = fx.build_plan(fx.EXACT_REFERENCE_FIXTURE_ID)
    assert {label.dataset_id for label in plan.source_labels} == {
        "mesc-pilot-01-synthetic-qualification"
    }, "every fixture must declare the synthetic dataset identity"
    assert criterion_by_key("no-real-p01-03g-membership").status == SATISFIED


def test_criterion_11_atomic_publication_not_applicable(
    exact_reference_result: FixtureSplitResult,
) -> None:
    """B2D creates no publication capability and none may be simulated."""
    criterion = criterion_by_key("atomic-publication")
    assert criterion.status == NOT_APPLICABLE
    assert criterion.status != SATISFIED, "NOT APPLICABLE must never convert to SATISFIED"
    assert "NOT SATISFIED for P01-04B overall" in criterion.p01_04b_consequence
    fields = set(FixtureSplitResult.__dataclass_fields__)
    assert not any("path" in name or "file" in name or "dir" in name for name in fields), (
        "the result must expose no filesystem publication surface"
    )
    assert isinstance(exact_reference_result.group_registry_bytes, bytes)


def test_criterion_12_write_path_protections_not_applicable() -> None:
    """B2D accepts no filesystem path and performs no write."""
    criterion = criterion_by_key("write-path-protections")
    assert criterion.status == NOT_APPLICABLE
    assert criterion.status != SATISFIED, "NOT APPLICABLE must never convert to SATISFIED"
    assert "NOT SATISFIED for P01-04B overall" in criterion.p01_04b_consequence
    fields = set(FixtureSplitRequest.__dataclass_fields__)
    assert not any("path" in name or "file" in name or "dir" in name for name in fields), (
        "the request must accept no filesystem input or output path"
    )
    with pytest.raises(InvalidFixtureRequestError):
        build_request(fx.EXACT_REFERENCE_FIXTURE_ID, policy_id="./local/policy")


def test_criterion_13_date_free_canonical_byte_surfaces(
    results: dict[str, FixtureSplitResult],
) -> None:
    """The date-free byte invariant is testable; it does not make output promotable."""
    forbidden = (
        b"date",
        b"timestamp",
        b"created_at",
        b"generated_at",
        b"hostname",
        b"username",
        b"workspace",
        b"workflow",
        b"duration",
        b"elapsed",
        b"cwd",
        b"runtime",
        b"command",
    )
    for fixture_id in SUCCESSFUL_FIXTURE_IDS:
        for role, payload in byte_surfaces(results[fixture_id]).items():
            lowered = payload.lower()
            for token in forbidden:
                assert token not in lowered, (
                    f"{fixture_id} {role} carries the forbidden runtime token {token!r}"
                )
    criterion = criterion_by_key("date-free-promotable-artifacts")
    assert criterion.status == NOT_APPLICABLE
    assert criterion.status != SATISFIED, "NOT APPLICABLE must never convert to SATISFIED"
    assert "does not" in criterion.p01_04b_consequence


def test_the_mapping_covers_exactly_thirteen_unique_criteria() -> None:
    numbered = [criterion for criterion in P01_04B_CRITERIA if criterion.number is not None]
    assert len(numbered) == UNIQUE_CRITERION_COUNT, (
        f"the mapping must cover exactly {UNIQUE_CRITERION_COUNT} unique criteria"
    )
    assert [criterion.number for criterion in numbered] == list(range(1, 14))
    assert len({criterion.key for criterion in P01_04B_CRITERIA}) == len(P01_04B_CRITERIA)


def test_the_mapping_includes_the_three_non_duplicative_future_code_criteria() -> None:
    keys = {criterion.key for criterion in P01_04B_CRITERIA}
    assert {
        "atomic-publication",
        "write-path-protections",
        "date-free-promotable-artifacts",
    } <= keys, (
        "the ten tooling rows alone do not represent every canonical criterion; the three "
        "non-duplicative future-code criteria must be mapped separately"
    )


def test_every_criterion_status_is_in_the_allowed_domain() -> None:
    for criterion in P01_04B_CRITERIA:
        assert criterion.status in ALLOWED_STATUSES, (
            f"criterion {criterion.key!r} has status {criterion.status!r}, "
            f"which is outside {ALLOWED_STATUSES}"
        )


def test_every_criterion_names_a_test_symbol_defined_in_this_module() -> None:
    for criterion in P01_04B_CRITERIA:
        assert criterion.test_symbol in globals(), (
            f"criterion {criterion.key!r} names {criterion.test_symbol!r}, "
            "which is not defined in this module"
        )


def test_the_required_bounded_dispositions_are_recorded() -> None:
    assert criterion_by_key("indivisible-group-minimum-deviation").status == UNSATISFIED
    assert criterion_by_key("atomic-publication").status == NOT_APPLICABLE
    assert criterion_by_key("write-path-protections").status == NOT_APPLICABLE
    assert criterion_by_key("date-free-promotable-artifacts").status == NOT_APPLICABLE
    for number in range(1, 11):
        criterion = next(c for c in P01_04B_CRITERIA if c.number == number)
        assert criterion.status == SATISFIED, (
            f"tooling criterion {number} must be SATISFIED, got {criterion.status}"
        )


def test_not_applicable_never_converts_to_satisfied() -> None:
    inapplicable = [c for c in P01_04B_CRITERIA if c.status == NOT_APPLICABLE]
    assert len(inapplicable) == 3
    assert acceptance_eligible(tuple(inapplicable)) is False, (
        "a NOT APPLICABLE disposition must never count toward acceptance"
    )


def test_no_aggregate_may_accept_while_a_criterion_is_unsatisfied() -> None:
    unsatisfied = [c for c in P01_04B_CRITERIA if c.status in (UNSATISFIED, BLOCKED)]
    assert unsatisfied, "the minimum-deviation criterion must be recorded as unsatisfied"
    assert acceptance_eligible(P01_04B_CRITERIA) is False


def test_p01_04b_acceptance_eligibility_is_false() -> None:
    assert acceptance_eligible(P01_04B_CRITERIA) is P01_04B_ACCEPTANCE_ELIGIBILITY is False
    assert P01_04B_ACCEPTANCE_RECOMMENDATION == "CHANGES REQUIRED"
    assert P01_04B_STATUS == "INCOMPLETE / NOT ACCEPTED"


def test_green_qualification_ci_does_not_equal_p01_04b_acceptance() -> None:
    assert GREEN_CI_MEANING == "GREEN B2D QUALIFICATION CI DOES NOT EQUAL P01-04B ACCEPTANCE"
    assert P01_04B_ACCEPTANCE_ELIGIBILITY is False, (
        "passing this suite makes B2D eligible for a separate founder disposition only"
    )
