"""P01-04C synthetic fixture qualification over the accepted P01-04B tooling.

This module is a *qualification candidate*.  It builds deterministic synthetic
fixtures, runs the accepted private ``FixtureSplitFacade`` over them, and
compares every runtime value against literal constants transcribed once from a
local inspection run.  Nothing here is canonical evidence, research evidence or
a real split artifact.

Scope boundaries this module never crosses: no real dataset is opened, no
P01-03G registry membership is read or generated, no artifact is written, no
network is used, and the public ``SourceDocumentGroupedSplitter.assign``
remains unconditionally fail-closed.

Every expected value below is a literal.  No expectation is derived from the
result under test, and no test regenerates or updates a golden automatically.
"""

from __future__ import annotations

import builtins
import contextlib
import hashlib
import io
import os
import pathlib
import random
import socket
import subprocess
import time
from collections.abc import Iterator, Mapping
from typing import Final

import pytest

from medscale.mesc._fixture_split_v1 import (
    FIXTURE_NAMESPACE_PREFIX,
    FixtureSplitFacade,
    FixtureSplitRequest,
    FixtureSplitResult,
    InvalidFixtureRequestError,
)
from medscale.mesc._split_v1 import SPLIT_SEED, Decision, OrderedExampleRow, SourceLabelRow
from medscale.mesc.split import PilotSplitNotAuthorizedError, SourceDocumentGroupedSplitter

# ---------------------------------------------------------------------------
# Qualification contract
# ---------------------------------------------------------------------------
#
# C1  every dedicated fixture test passes for deterministic synthetic small input
# C2  every successful fixture produces byte-identical output on repeated runs
# C3  empty / single-example / all-one-label edge cases pass under the ratified
#     semantics: empty is EXPECTED FAIL-CLOSED, single-example is EXPECTED
#     SUCCESS, all-one-label is EXPECTED SUCCESS
# C4  no real dataset partition membership is generated
#
# Passing this module is qualification evidence only.  It is not P01-04C
# acceptance, and it authorizes no real dataset execution and no P01-04D work.

#: Wholly synthetic provenance.  These are not real dataset identities and
#: resolve to no real corpus, revision, configuration or registry.
DATASET_ID: Final = "mesc-p01-04c-synthetic-dataset"
DATASET_REVISION: Final = "p01-04c-synthetic-revision-1"
CONFIGURATION: Final = "p01-04c-synthetic-configuration"
POLICY_ID: Final = "mesc-pilot-01-p01-04c-qualification-policy/1"
TRANSFORMATION_VERSION: Final = "mesc-pilot-01-p01-04c-transformation/1"
EXECUTION_EVIDENCE_REF: Final = "mesc-pilot-01-p01-04c-fixture-qualification/1"

#: Both entries are members of the accepted B2B detection-method allowlist.
DETECTION_METHODS: Final = ("exact_example_identity", "exact_source_document_identity")

#: The ratified 20-row decision assignment, by row ordinal: 00-07 yes, 08-14 no,
#: 15-19 maybe, giving exactly yes 8 / no 7 / maybe 5.
SMALL_20_DECISIONS: Final[tuple[Decision, ...]] = (
    "yes",
    "yes",
    "yes",
    "yes",
    "yes",
    "yes",
    "yes",
    "yes",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "maybe",
    "maybe",
    "maybe",
    "maybe",
    "maybe",
)

#: Twenty rows that all carry the same decision.
ALL_ONE_LABEL_20_DECISIONS: Final[tuple[Decision, ...]] = ("yes",) * 20

#: Exactly one row.
SINGLE_EXAMPLE_DECISIONS: Final[tuple[Decision, ...]] = ("yes",)

TWENTY_ROW_TOTALS: Final[Mapping[str, int]] = {"train": 14, "validation": 3, "test": 3}
SINGLE_ROW_TOTALS: Final[Mapping[str, int]] = {"train": 1, "validation": 0, "test": 0}
EMPTY_TOTALS: Final[Mapping[str, int]] = {"train": 0, "validation": 0, "test": 0}

SYNTHETIC_PROOF_PREFIX: Final = "mesc-synthetic-batch/1:sha256:"
REQUEST_ID_PREFIX: Final = "mesc-pilot-01-fixture-request/1:sha256:"

# ---------------------------------------------------------------------------
# Frozen qualification vectors
# ---------------------------------------------------------------------------
#
# Transcribed once from a local inspection run and never regenerated by a test.
# An independent reviewer verifies each literal against a clean-room run.

SMALL_20_FIXTURE_ID: Final = "p01-04c-small-20-v1"
SMALL_20_FIXTURE_SHA256: Final = "3b95e70f2b82129556d81f6a8b9ece80d01c314ded57d6cfa2e7c176d452d821"
SMALL_20_REQUEST_ID: Final = (
    REQUEST_ID_PREFIX + "65a4f736763287b34334e44516c03f495d2f005c3849472b82082c1861c19e27"
)
SMALL_20_SPLIT_HASH: Final = "d451adc740e54b28"
SMALL_20_SPLIT_FINGERPRINT: Final = (
    "6c8ca75dbccaf92a4501bd86d1b3c1150ded22cf28cf39696e7f864f2073ef54"
)
SMALL_20_SURFACES: Final[Mapping[str, tuple[str, int]]] = {
    "group_registry_bytes": (
        "d68f1e4d4e4e0457d992cdfaa49e2d26fdeef2f123279120eb7da3cabfffcbf7",
        6962,
    ),
    "example_registry_bytes": (
        "5d5250261593d82158a3fde480d0025bf9f549b4106b06eac625f7b6bfbeefee",
        6322,
    ),
    "excluded_ledger_bytes": (
        "786ba24fd619636052cfb3bd42b49f7bcaeb481e3745a8becb626dc064d80050",
        97,
    ),
    "split_summary_identity_core_bytes": (
        "d8f2c264c2952e066661f64107ff6ed0282cb4068f31c3c910c83b4f9b385655",
        492,
    ),
    "split_summary_document_bytes": (
        "3373f5676dcae0c9fda8315bb9334340f141e6e489846e2bfe8330177e4f7365",
        597,
    ),
    "audit_report_bytes": (
        "cfbd0134bc007b69603d6178dd06b3410af57823ac3261d00e4206b2e2ebfd58",
        351,
    ),
}
SMALL_20_LABEL_TOTALS: Final[Mapping[str, int]] = {"yes": 8, "no": 7, "maybe": 5}
SMALL_20_MATRIX: Final[Mapping[str, Mapping[str, int]]] = {
    "train": {"yes": 6, "no": 5, "maybe": 3},
    "validation": {"yes": 1, "no": 1, "maybe": 1},
    "test": {"yes": 1, "no": 1, "maybe": 1},
}

SINGLE_FIXTURE_ID: Final = "p01-04c-single-example-v1"
SINGLE_FIXTURE_SHA256: Final = "2d52d8dd9ce964e69d8dc49cfa9239e583352c854cdc1cf77399db20a849b65f"
SINGLE_REQUEST_ID: Final = (
    REQUEST_ID_PREFIX + "4fca9992942ee903f0e36bc2b0676d04a928cdac3c8553ef1babcb7553401013"
)
SINGLE_SPLIT_HASH: Final = "fed2add59657a094"
SINGLE_SPLIT_FINGERPRINT: Final = "5094ece610c3a5e6ed3da9b707f074e2101b31e61b2c6950e2ca2c7e8017659d"
SINGLE_SURFACES: Final[Mapping[str, tuple[str, int]]] = {
    "group_registry_bytes": (
        "c0b401c74f2edc215a1c8b0b6c15b8f717ef74cc3f05b3f590560394c710b459",
        347,
    ),
    "example_registry_bytes": (
        "9ea7fbdb2cbf09c2957c43f8aaa30bdc6aadfbc43da930ac73580a1cd752e598",
        315,
    ),
    "excluded_ledger_bytes": (
        "786ba24fd619636052cfb3bd42b49f7bcaeb481e3745a8becb626dc064d80050",
        97,
    ),
    "split_summary_identity_core_bytes": (
        "8110bc21939ec6ad34433ac650582176131dfd27abd75bde6130ecf09e532aad",
        488,
    ),
    "split_summary_document_bytes": (
        "7e28dacd31cb1773d0646e709311cb6003b19649cec34d057195e838e8ab9634",
        593,
    ),
    "audit_report_bytes": (
        "cfbd0134bc007b69603d6178dd06b3410af57823ac3261d00e4206b2e2ebfd58",
        351,
    ),
}
SINGLE_LABEL_TOTALS: Final[Mapping[str, int]] = {"yes": 1, "no": 0, "maybe": 0}
SINGLE_MATRIX: Final[Mapping[str, Mapping[str, int]]] = {
    "train": {"yes": 1, "no": 0, "maybe": 0},
    "validation": {"yes": 0, "no": 0, "maybe": 0},
    "test": {"yes": 0, "no": 0, "maybe": 0},
}

ALL_ONE_FIXTURE_ID: Final = "p01-04c-all-one-label-20-v1"
ALL_ONE_FIXTURE_SHA256: Final = "d0c505a39712632f20df8a80bb2c5931481f99ce1180d5b30df0513b3d6f6719"
ALL_ONE_REQUEST_ID: Final = (
    REQUEST_ID_PREFIX + "3607e24fd5478043606445b150912e775ea655325687988931247eb6dcdf973b"
)
ALL_ONE_SPLIT_HASH: Final = "7a6e06cfb1b71aa3"
ALL_ONE_SPLIT_FINGERPRINT: Final = (
    "7aba158a3ddffbbfb230fe7e72acf633cbf1c5b67f41805643a2796812ed64d9"
)
ALL_ONE_SURFACES: Final[Mapping[str, tuple[str, int]]] = {
    "group_registry_bytes": (
        "4c9dcffa75f9ea1ce2c0192120ea3ba7834bbafc6389b3ef14155cd95fdd44e6",
        6962,
    ),
    "example_registry_bytes": (
        "fb2bc6060a6961cd5683df23e5c7441a83496e7544de402ca7ca8455110bddce",
        6322,
    ),
    "excluded_ledger_bytes": (
        "786ba24fd619636052cfb3bd42b49f7bcaeb481e3745a8becb626dc064d80050",
        97,
    ),
    "split_summary_identity_core_bytes": (
        "7ef665533ba2eaf958b033ab62f01a7e97a1dceeed0bf88ba58bd03508f46f2d",
        494,
    ),
    "split_summary_document_bytes": (
        "78a30c42a27252b67d7cbb100972b0338df1bb19cf3f4ab5995b355678197d0e",
        599,
    ),
    "audit_report_bytes": (
        "cfbd0134bc007b69603d6178dd06b3410af57823ac3261d00e4206b2e2ebfd58",
        351,
    ),
}
ALL_ONE_LABEL_TOTALS: Final[Mapping[str, int]] = {"yes": 20, "no": 0, "maybe": 0}
ALL_ONE_MATRIX: Final[Mapping[str, Mapping[str, int]]] = {
    "train": {"yes": 14, "no": 0, "maybe": 0},
    "validation": {"yes": 3, "no": 0, "maybe": 0},
    "test": {"yes": 3, "no": 0, "maybe": 0},
}

#: Literal descriptor expectations, in role-ascending canonical order.
SMALL_20_DESCRIPTORS: Final[tuple[tuple[str, str, str, int], ...]] = (
    (
        "example_registry",
        "mesc-pilot-01-example-registry/1",
        "5d5250261593d82158a3fde480d0025bf9f549b4106b06eac625f7b6bfbeefee",
        6322,
    ),
    (
        "excluded_ledger",
        "mesc-pilot-01-excluded-ledger/1",
        "786ba24fd619636052cfb3bd42b49f7bcaeb481e3745a8becb626dc064d80050",
        97,
    ),
    (
        "group_registry",
        "mesc-pilot-01-group-registry/1",
        "d68f1e4d4e4e0457d992cdfaa49e2d26fdeef2f123279120eb7da3cabfffcbf7",
        6962,
    ),
    (
        "split_summary",
        "mesc-pilot-01-split-summary-identity-core/1",
        "d8f2c264c2952e066661f64107ff6ed0282cb4068f31c3c910c83b4f9b385655",
        492,
    ),
)

BYTE_SURFACE_NAMES: Final = (
    "group_registry_bytes",
    "example_registry_bytes",
    "excluded_ledger_bytes",
    "split_summary_identity_core_bytes",
    "split_summary_document_bytes",
    "audit_report_bytes",
)

_HEX_DIGITS: Final = frozenset("0123456789abcdef")


# ---------------------------------------------------------------------------
# Deterministic synthetic request construction
# ---------------------------------------------------------------------------


def _source_record_hash(ordinal: int) -> str:
    """Return a synthetic 64-hex record hash derived only from the row ordinal."""
    return hashlib.sha256(f"mesc-p01-04c-source-record:{ordinal:02d}".encode()).hexdigest()


def _synthetic_proof(fixture_id: str) -> str:
    """Return the declared synthetic-batch marker for a fixture identifier."""
    digest = hashlib.sha256(f"mesc-p01-04c-synthetic-batch:{fixture_id}".encode()).hexdigest()
    return SYNTHETIC_PROOF_PREFIX + digest


def _ordered_rows(count: int) -> tuple[OrderedExampleRow, ...]:
    return tuple(
        OrderedExampleRow(
            original_example_id=f"p01-04c-example-{ordinal:02d}",
            row_ordinal=ordinal,
            source_document_id=f"p01-04c-document-{ordinal:02d}",
        )
        for ordinal in range(count)
    )


def _source_labels(decisions: tuple[Decision, ...]) -> tuple[SourceLabelRow, ...]:
    return tuple(
        SourceLabelRow(
            dataset_id=DATASET_ID,
            dataset_revision=DATASET_REVISION,
            configuration=CONFIGURATION,
            original_example_id=f"p01-04c-example-{ordinal:02d}",
            source_document_id=f"p01-04c-document-{ordinal:02d}",
            decision=decision,
            source_record_hash=_source_record_hash(ordinal),
        )
        for ordinal, decision in enumerate(decisions)
    )


def _build_request(
    *,
    fixture_id: str,
    decisions: tuple[Decision, ...],
    partition_totals: Mapping[str, int],
    fixture_sha256: str,
    request_id: str,
) -> FixtureSplitRequest:
    """Return a fresh synthetic request built only from literal inputs.

    ``fixture_sha256`` and ``request_id`` are supplied as frozen literals rather
    than recomputed here, so the facade's identity verification is a real check
    against a transcribed constant instead of a tautology.
    """
    return FixtureSplitRequest(
        fixture_schema_version="1",
        fixture_namespace=FIXTURE_NAMESPACE_PREFIX + fixture_id,
        fixture_id=fixture_id,
        fixture_sha256=fixture_sha256,
        fixture_only=True,
        non_evidence=True,
        synthetic_identity_proof=_synthetic_proof(fixture_id),
        request_id=request_id,
        seed=SPLIT_SEED,
        policy_id=POLICY_ID,
        transformation_version=TRANSFORMATION_VERSION,
        ordered_rows=_ordered_rows(len(decisions)),
        source_labels=_source_labels(decisions),
        partition_totals=dict(partition_totals),
        leakage_findings=(),
        detection_methods=DETECTION_METHODS,
        execution_evidence_ref=EXECUTION_EVIDENCE_REF,
    )


def _small_20_request() -> FixtureSplitRequest:
    return _build_request(
        fixture_id=SMALL_20_FIXTURE_ID,
        decisions=SMALL_20_DECISIONS,
        partition_totals=TWENTY_ROW_TOTALS,
        fixture_sha256=SMALL_20_FIXTURE_SHA256,
        request_id=SMALL_20_REQUEST_ID,
    )


def _single_example_request() -> FixtureSplitRequest:
    return _build_request(
        fixture_id=SINGLE_FIXTURE_ID,
        decisions=SINGLE_EXAMPLE_DECISIONS,
        partition_totals=SINGLE_ROW_TOTALS,
        fixture_sha256=SINGLE_FIXTURE_SHA256,
        request_id=SINGLE_REQUEST_ID,
    )


def _all_one_label_request() -> FixtureSplitRequest:
    return _build_request(
        fixture_id=ALL_ONE_FIXTURE_ID,
        decisions=ALL_ONE_LABEL_20_DECISIONS,
        partition_totals=TWENTY_ROW_TOTALS,
        fixture_sha256=ALL_ONE_FIXTURE_SHA256,
        request_id=ALL_ONE_REQUEST_ID,
    )


# ---------------------------------------------------------------------------
# Side-effect boundary
# ---------------------------------------------------------------------------


class SideEffectAttemptError(AssertionError):
    """Raised when guarded code attempts a prohibited side-effect channel."""


class _ForbiddenEnviron(Mapping[str, str]):
    """An environment mapping that refuses every read."""

    def __getitem__(self, key: str) -> str:
        raise SideEffectAttemptError("environment read attempted")

    def __iter__(self) -> Iterator[str]:
        raise SideEffectAttemptError("environment iteration attempted")

    def __len__(self) -> int:
        raise SideEffectAttemptError("environment length read attempted")


def _forbid(channel: str) -> object:
    def _refuse(*args: object, **kwargs: object) -> object:
        raise SideEffectAttemptError(f"{channel} attempted")

    return _refuse


@contextlib.contextmanager
def _side_effect_boundary() -> Iterator[None]:
    """Disable filesystem, socket, subprocess, clock, environment and randomness.

    Restoration happens in ``finally`` before any assertion runs, so a failing
    expectation is reported normally instead of tripping the guard itself.
    """
    targets: tuple[tuple[object, str, object], ...] = (
        (builtins, "open", _forbid("filesystem open")),
        (io, "open", _forbid("filesystem open")),
        (pathlib.Path, "open", _forbid("path open")),
        (pathlib.Path, "write_text", _forbid("path write")),
        (pathlib.Path, "write_bytes", _forbid("path write")),
        (os, "remove", _forbid("filesystem unlink")),
        (os, "urandom", _forbid("urandom")),
        (os, "getenv", _forbid("environment read")),
        (os, "environ", _ForbiddenEnviron()),
        (socket, "socket", _forbid("socket creation")),
        (socket, "create_connection", _forbid("socket connection")),
        (subprocess, "Popen", _forbid("subprocess execution")),
        (subprocess, "run", _forbid("subprocess execution")),
        (time, "time", _forbid("clock access")),
        (time, "time_ns", _forbid("clock access")),
        (time, "monotonic", _forbid("clock access")),
        (random, "random", _forbid("randomness")),
        (random, "randint", _forbid("randomness")),
        (random, "choice", _forbid("randomness")),
    )
    saved = [(holder, name, getattr(holder, name)) for holder, name, _ in targets]
    try:
        for holder, name, replacement in targets:
            setattr(holder, name, replacement)
        yield
    finally:
        for holder, name, original in saved:
            setattr(holder, name, original)


def _run_guarded(request: FixtureSplitRequest) -> FixtureSplitResult:
    with _side_effect_boundary():
        return FixtureSplitFacade.run(request)


# ---------------------------------------------------------------------------
# Shared expectation helpers
# ---------------------------------------------------------------------------


def _assert_surfaces(result: FixtureSplitResult, expected: Mapping[str, tuple[str, int]]) -> None:
    for name in BYTE_SURFACE_NAMES:
        payload = getattr(result, name)
        assert type(payload) is bytes
        expected_digest, expected_size = expected[name]
        assert hashlib.sha256(payload).hexdigest() == expected_digest
        assert len(payload) == expected_size
        assert payload.endswith(b"\n")
        assert not payload.endswith(b"\n\n")


def _assert_no_real_membership(result: FixtureSplitResult) -> None:
    """Every assigned identity must trace back to a synthetic P01-04C row."""
    for assignment in result.split_manifest.split_assignments:
        assert assignment.source_document_id.startswith("p01-04c-document-")
        assert assignment.split in {"train", "validation", "test"}


# ---------------------------------------------------------------------------
# Small-20 fixture
# ---------------------------------------------------------------------------


def test_small_20_fixture_matches_frozen_vectors() -> None:
    request = _small_20_request()
    assert request.fixture_id == SMALL_20_FIXTURE_ID
    assert len(request.ordered_rows) == 20
    assert len({row.source_document_id for row in request.ordered_rows}) == 20

    result = _run_guarded(request)

    assert result.request_id == SMALL_20_REQUEST_ID
    assert result.split_manifest.computed_split_hash == SMALL_20_SPLIT_HASH
    assert result.split_fingerprint_record.split_fingerprint == SMALL_20_SPLIT_FINGERPRINT
    _assert_surfaces(result, SMALL_20_SURFACES)


def test_small_20_identity_core_matches_frozen_counts() -> None:
    core = _run_guarded(_small_20_request()).split_summary_identity_core
    assert core.total_example_count == 20
    assert core.total_group_count == 20
    assert core.excluded_record_count == 0
    assert dict(core.partition_totals) == dict(TWENTY_ROW_TOTALS)
    assert dict(core.group_counts_by_partition) == dict(TWENTY_ROW_TOTALS)
    assert dict(core.label_totals) == dict(SMALL_20_LABEL_TOTALS)
    assert {partition: dict(row) for partition, row in core.partition_label_matrix.items()} == {
        partition: dict(row) for partition, row in SMALL_20_MATRIX.items()
    }


def test_small_20_descriptors_match_frozen_literals() -> None:
    record = _run_guarded(_small_20_request()).split_fingerprint_record
    observed = tuple(
        (item.role, item.schema_version, item.sha256, item.byte_size)
        for item in record.identity.artifact_descriptors
    )
    assert observed == SMALL_20_DESCRIPTORS


def test_small_20_audit_report_is_clean_and_unsuppressed() -> None:
    report = _run_guarded(_small_20_request()).audit_report
    assert report.finding_count == 0
    assert report.leaked is False
    assert report.findings == ()
    assert report.detection_methods == DETECTION_METHODS


def test_small_20_fingerprint_and_hash_shapes_are_exact() -> None:
    result = _run_guarded(_small_20_request())
    fingerprint = result.split_fingerprint_record.split_fingerprint
    split_hash = result.split_manifest.computed_split_hash
    assert len(fingerprint) == 64
    assert set(fingerprint) <= _HEX_DIGITS
    assert len(split_hash) == 16
    assert set(split_hash) <= _HEX_DIGITS
    assert fingerprint != split_hash


# ---------------------------------------------------------------------------
# Repeated-run byte identity
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("builder", "expected_request_id", "expected_hash", "expected_fingerprint"),
    [
        (_small_20_request, SMALL_20_REQUEST_ID, SMALL_20_SPLIT_HASH, SMALL_20_SPLIT_FINGERPRINT),
        (
            _single_example_request,
            SINGLE_REQUEST_ID,
            SINGLE_SPLIT_HASH,
            SINGLE_SPLIT_FINGERPRINT,
        ),
        (
            _all_one_label_request,
            ALL_ONE_REQUEST_ID,
            ALL_ONE_SPLIT_HASH,
            ALL_ONE_SPLIT_FINGERPRINT,
        ),
    ],
)
def test_three_fresh_runs_are_byte_identical(
    builder: object,
    expected_request_id: str,
    expected_hash: str,
    expected_fingerprint: str,
) -> None:
    """Three fresh, semantically identical requests must agree on every surface."""
    assert callable(builder)
    requests = [builder() for _ in range(3)]
    assert len({id(item) for item in requests}) == 3
    results = [_run_guarded(item) for item in requests]

    first = results[0]
    for other in results[1:]:
        assert other.request_id == first.request_id
        assert other.split_manifest.computed_split_hash == first.split_manifest.computed_split_hash
        assert (
            other.split_fingerprint_record.split_fingerprint
            == first.split_fingerprint_record.split_fingerprint
        )
        assert other.split_manifest.split_assignments == first.split_manifest.split_assignments
        for name in BYTE_SURFACE_NAMES:
            assert getattr(other, name) == getattr(first, name)
        observed = tuple(
            (item.role, item.sha256, item.byte_size)
            for item in other.split_fingerprint_record.identity.artifact_descriptors
        )
        baseline = tuple(
            (item.role, item.sha256, item.byte_size)
            for item in first.split_fingerprint_record.identity.artifact_descriptors
        )
        assert observed == baseline

    for item in requests:
        assert item.fixture_sha256 == requests[0].fixture_sha256
    assert first.request_id == expected_request_id
    assert first.split_manifest.computed_split_hash == expected_hash
    assert first.split_fingerprint_record.split_fingerprint == expected_fingerprint


# ---------------------------------------------------------------------------
# Empty-input fail-closed behavior
# ---------------------------------------------------------------------------


def _empty_request() -> FixtureSplitRequest:
    """Construct the zero-row request; construction itself must fail closed."""
    return FixtureSplitRequest(
        fixture_schema_version="1",
        fixture_namespace=FIXTURE_NAMESPACE_PREFIX + "p01-04c-empty-v1",
        fixture_id="p01-04c-empty-v1",
        fixture_sha256="0" * 64,
        fixture_only=True,
        non_evidence=True,
        synthetic_identity_proof=_synthetic_proof("p01-04c-empty-v1"),
        request_id=REQUEST_ID_PREFIX + "0" * 64,
        seed=SPLIT_SEED,
        policy_id=POLICY_ID,
        transformation_version=TRANSFORMATION_VERSION,
        ordered_rows=(),
        source_labels=(),
        partition_totals=dict(EMPTY_TOTALS),
        leakage_findings=(),
        detection_methods=DETECTION_METHODS,
        execution_evidence_ref=EXECUTION_EVIDENCE_REF,
    )


def test_empty_input_fails_closed_three_times_identically() -> None:
    """Empty input is EXPECTED FAIL-CLOSED, not an expected successful split."""
    codes: list[str] = []
    messages: list[str] = []
    for _ in range(3):
        with pytest.raises(InvalidFixtureRequestError) as caught:
            _empty_request()
        assert type(caught.value) is InvalidFixtureRequestError
        codes.append(caught.value.code)
        messages.append(str(caught.value))

    assert codes == ["invalid_fixture_request"] * 3
    assert len(set(messages)) == 1
    assert messages[0] == "ordered_rows must be a non-empty exact tuple"


def test_empty_input_emits_no_artifact_and_no_write() -> None:
    with _side_effect_boundary(), pytest.raises(InvalidFixtureRequestError):
        _empty_request()


def test_non_empty_request_invariant_is_not_weakened() -> None:
    """A zero-row request must never become constructible."""
    with pytest.raises(InvalidFixtureRequestError):
        _empty_request()


# ---------------------------------------------------------------------------
# Single-example behavior
# ---------------------------------------------------------------------------


def test_single_example_is_expected_success() -> None:
    request = _single_example_request()
    assert len(request.ordered_rows) == 1
    assert len(request.source_labels) == 1

    result = _run_guarded(request)

    assert result.request_id == SINGLE_REQUEST_ID
    assert result.split_manifest.computed_split_hash == SINGLE_SPLIT_HASH
    assert result.split_fingerprint_record.split_fingerprint == SINGLE_SPLIT_FINGERPRINT
    _assert_surfaces(result, SINGLE_SURFACES)


def test_single_example_is_assigned_exactly_once_to_train() -> None:
    result = _run_guarded(_single_example_request())
    assignments = result.split_manifest.split_assignments
    assert len(assignments) == 1
    assert assignments[0].split == "train"
    assert assignments[0].source_document_id == "p01-04c-document-00"
    assert len({item.example_id for item in assignments}) == 1


def test_single_example_identity_shapes_and_counts() -> None:
    result = _run_guarded(_single_example_request())
    core = result.split_summary_identity_core
    fingerprint = result.split_fingerprint_record.split_fingerprint
    split_hash = result.split_manifest.computed_split_hash
    assert len(fingerprint) == 64
    assert set(fingerprint) <= _HEX_DIGITS
    assert len(split_hash) == 16
    assert set(split_hash) <= _HEX_DIGITS
    assert core.total_example_count == 1
    assert core.total_group_count == 1
    assert dict(core.partition_totals) == dict(SINGLE_ROW_TOTALS)
    assert dict(core.label_totals) == dict(SINGLE_LABEL_TOTALS)
    assert {partition: dict(row) for partition, row in core.partition_label_matrix.items()} == {
        partition: dict(row) for partition, row in SINGLE_MATRIX.items()
    }
    _assert_no_real_membership(result)


# ---------------------------------------------------------------------------
# All-one-label behavior
# ---------------------------------------------------------------------------


def test_all_one_label_is_expected_success() -> None:
    request = _all_one_label_request()
    assert len(request.ordered_rows) == 20
    assert {label.decision for label in request.source_labels} == {"yes"}

    result = _run_guarded(request)

    assert result.request_id == ALL_ONE_REQUEST_ID
    assert result.split_manifest.computed_split_hash == ALL_ONE_SPLIT_HASH
    assert result.split_fingerprint_record.split_fingerprint == ALL_ONE_SPLIT_FINGERPRINT
    _assert_surfaces(result, ALL_ONE_SURFACES)


def test_all_one_label_totals_and_group_indivisibility() -> None:
    result = _run_guarded(_all_one_label_request())
    core = result.split_summary_identity_core
    assert dict(core.label_totals) == dict(ALL_ONE_LABEL_TOTALS)
    assert dict(core.partition_totals) == dict(TWENTY_ROW_TOTALS)
    assert dict(core.group_counts_by_partition) == dict(TWENTY_ROW_TOTALS)
    assert {partition: dict(row) for partition, row in core.partition_label_matrix.items()} == {
        partition: dict(row) for partition, row in ALL_ONE_MATRIX.items()
    }

    # Group indivisibility: every source document lands in exactly one partition.
    partitions_by_document: dict[str, set[str]] = {}
    for assignment in result.split_manifest.split_assignments:
        partitions_by_document.setdefault(assignment.source_document_id, set()).add(
            assignment.split
        )
    assert len(partitions_by_document) == 20
    assert all(len(splits) == 1 for splits in partitions_by_document.values())
    _assert_no_real_membership(result)


# ---------------------------------------------------------------------------
# Side-effect boundary
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "builder", [_small_20_request, _single_example_request, _all_one_label_request]
)
def test_success_path_needs_no_side_effect_channel(builder: object) -> None:
    """Every successful fixture runs with all prohibited channels disabled."""
    assert callable(builder)
    result = _run_guarded(builder())
    assert type(result) is FixtureSplitResult


def test_boundary_guard_itself_refuses_each_channel() -> None:
    """The guard must actually block, otherwise the boundary proves nothing."""
    with _side_effect_boundary():
        # Each channel is reached through an indirect reference so this probe
        # never contains a literal filesystem call of its own.
        opener = builtins.open
        connector = socket.socket
        runner = subprocess.run
        for attempt in (
            lambda: opener("x"),
            lambda: connector(),
            lambda: runner(["x"], check=False),
            time.time,
            random.random,
            lambda: os.urandom(1),
            lambda: os.environ["PATH"],
        ):
            try:
                attempt()
            except SideEffectAttemptError:
                continue
            raise AssertionError("a prohibited channel was not blocked")


def test_boundary_restores_every_channel_afterwards() -> None:
    before = (builtins.open, socket.socket, subprocess.run, time.time, os.urandom)
    with _side_effect_boundary():
        pass
    after = (builtins.open, socket.socket, subprocess.run, time.time, os.urandom)
    assert before == after
    assert isinstance(os.environ.get("PATH", ""), str)


# ---------------------------------------------------------------------------
# Public splitter preservation
# ---------------------------------------------------------------------------


def test_public_splitter_remains_unconditionally_fail_closed() -> None:
    splitter = SourceDocumentGroupedSplitter()
    for example_ids, document_ids in (
        ([], []),
        (["p01-04c-example-00"], ["p01-04c-document-00"]),
        (
            [f"p01-04c-example-{index:02d}" for index in range(20)],
            [f"p01-04c-document-{index:02d}" for index in range(20)],
        ),
    ):
        with pytest.raises(PilotSplitNotAuthorizedError):
            splitter.assign(example_ids, document_ids)


def test_public_splitter_is_untouched_by_fixture_execution() -> None:
    _run_guarded(_small_20_request())
    with pytest.raises(PilotSplitNotAuthorizedError):
        SourceDocumentGroupedSplitter().assign(["a"], ["b"])


# ---------------------------------------------------------------------------
# Scope and provenance assertions
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "builder", [_small_20_request, _single_example_request, _all_one_label_request]
)
def test_every_request_identity_is_synthetic(builder: object) -> None:
    assert callable(builder)
    request = builder()
    assert request.fixture_only is True
    assert request.non_evidence is True
    for row in request.ordered_rows:
        assert row.original_example_id.startswith("p01-04c-example-")
        assert row.source_document_id.startswith("p01-04c-document-")
    for label in request.source_labels:
        assert label.dataset_id == DATASET_ID
        assert label.dataset_revision == DATASET_REVISION
        assert label.configuration == CONFIGURATION
        assert len(label.source_record_hash) == 64
        assert set(label.source_record_hash) <= _HEX_DIGITS


@pytest.mark.parametrize(
    "builder", [_small_20_request, _single_example_request, _all_one_label_request]
)
def test_no_request_field_carries_a_path_or_external_reference(builder: object) -> None:
    assert callable(builder)
    request = builder()
    values = [
        request.fixture_namespace,
        request.fixture_id,
        request.policy_id,
        request.transformation_version,
        request.execution_evidence_ref,
        request.synthetic_identity_proof,
        DATASET_ID,
        DATASET_REVISION,
        CONFIGURATION,
    ]
    values.extend(row.original_example_id for row in request.ordered_rows)
    values.extend(row.source_document_id for row in request.ordered_rows)
    forbidden = ("://", "\\", "..", "~", "C:", "/home/", "/Users/")
    for value in values:
        assert not value.startswith(("/", "./"))
        for fragment in forbidden:
            assert fragment not in value


def test_no_payload_text_field_exists_on_the_request() -> None:
    """The accepted request type cannot carry question, context or answer text."""
    field_names = set(FixtureSplitRequest.__dataclass_fields__)
    for prohibited in ("question", "context", "answer", "long_answer", "text"):
        assert not any(prohibited in name for name in field_names)


def test_fixture_ids_are_the_three_authorized_qualification_fixtures() -> None:
    observed = {
        _small_20_request().fixture_id,
        _single_example_request().fixture_id,
        _all_one_label_request().fixture_id,
    }
    assert observed == {
        "p01-04c-small-20-v1",
        "p01-04c-single-example-v1",
        "p01-04c-all-one-label-20-v1",
    }
